// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package db_instance

import (
	"context"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go/aws"
	svcsdk "github.com/aws/aws-sdk-go/service/rds"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/rds-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &aws.JSONValue{}
	_ = &svcsdk.RDS{}
	_ = &svcapitypes.DBInstance{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer exit(err)
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadManyInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DescribeDBInstancesOutput
	resp, err = rm.sdkapi.DescribeDBInstancesWithContext(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "DescribeDBInstances", err)
	if err != nil {
		if awsErr, ok := ackerr.AWSError(err); ok && awsErr.Code() == "DBInstanceNotFound" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.DBInstances {
		if elem.ActivityStreamEngineNativeAuditFieldsIncluded != nil {
			ko.Status.ActivityStreamEngineNativeAuditFieldsIncluded = elem.ActivityStreamEngineNativeAuditFieldsIncluded
		} else {
			ko.Status.ActivityStreamEngineNativeAuditFieldsIncluded = nil
		}
		if elem.ActivityStreamKinesisStreamName != nil {
			ko.Status.ActivityStreamKinesisStreamName = elem.ActivityStreamKinesisStreamName
		} else {
			ko.Status.ActivityStreamKinesisStreamName = nil
		}
		if elem.ActivityStreamKmsKeyId != nil {
			ko.Status.ActivityStreamKMSKeyID = elem.ActivityStreamKmsKeyId
		} else {
			ko.Status.ActivityStreamKMSKeyID = nil
		}
		if elem.ActivityStreamMode != nil {
			ko.Status.ActivityStreamMode = elem.ActivityStreamMode
		} else {
			ko.Status.ActivityStreamMode = nil
		}
		if elem.ActivityStreamStatus != nil {
			ko.Status.ActivityStreamStatus = elem.ActivityStreamStatus
		} else {
			ko.Status.ActivityStreamStatus = nil
		}
		if elem.AllocatedStorage != nil {
			ko.Spec.AllocatedStorage = elem.AllocatedStorage
		} else {
			ko.Spec.AllocatedStorage = nil
		}
		if elem.AssociatedRoles != nil {
			f6 := []*svcapitypes.DBInstanceRole{}
			for _, f6iter := range elem.AssociatedRoles {
				f6elem := &svcapitypes.DBInstanceRole{}
				if f6iter.FeatureName != nil {
					f6elem.FeatureName = f6iter.FeatureName
				}
				if f6iter.RoleArn != nil {
					f6elem.RoleARN = f6iter.RoleArn
				}
				if f6iter.Status != nil {
					f6elem.Status = f6iter.Status
				}
				f6 = append(f6, f6elem)
			}
			ko.Status.AssociatedRoles = f6
		} else {
			ko.Status.AssociatedRoles = nil
		}
		if elem.AutoMinorVersionUpgrade != nil {
			ko.Spec.AutoMinorVersionUpgrade = elem.AutoMinorVersionUpgrade
		} else {
			ko.Spec.AutoMinorVersionUpgrade = nil
		}
		if elem.AutomaticRestartTime != nil {
			ko.Status.AutomaticRestartTime = &metav1.Time{*elem.AutomaticRestartTime}
		} else {
			ko.Status.AutomaticRestartTime = nil
		}
		if elem.AutomationMode != nil {
			ko.Status.AutomationMode = elem.AutomationMode
		} else {
			ko.Status.AutomationMode = nil
		}
		if elem.AvailabilityZone != nil {
			ko.Spec.AvailabilityZone = elem.AvailabilityZone
		} else {
			ko.Spec.AvailabilityZone = nil
		}
		if elem.AwsBackupRecoveryPointArn != nil {
			ko.Status.AWSBackupRecoveryPointARN = elem.AwsBackupRecoveryPointArn
		} else {
			ko.Status.AWSBackupRecoveryPointARN = nil
		}
		if elem.BackupRetentionPeriod != nil {
			ko.Spec.BackupRetentionPeriod = elem.BackupRetentionPeriod
		} else {
			ko.Spec.BackupRetentionPeriod = nil
		}
		if elem.CACertificateIdentifier != nil {
			ko.Status.CACertificateIdentifier = elem.CACertificateIdentifier
		} else {
			ko.Status.CACertificateIdentifier = nil
		}
		if elem.CharacterSetName != nil {
			ko.Spec.CharacterSetName = elem.CharacterSetName
		} else {
			ko.Spec.CharacterSetName = nil
		}
		if elem.CopyTagsToSnapshot != nil {
			ko.Spec.CopyTagsToSnapshot = elem.CopyTagsToSnapshot
		} else {
			ko.Spec.CopyTagsToSnapshot = nil
		}
		if elem.CustomIamInstanceProfile != nil {
			ko.Spec.CustomIAMInstanceProfile = elem.CustomIamInstanceProfile
		} else {
			ko.Spec.CustomIAMInstanceProfile = nil
		}
		if elem.CustomerOwnedIpEnabled != nil {
			ko.Status.CustomerOwnedIPEnabled = elem.CustomerOwnedIpEnabled
		} else {
			ko.Status.CustomerOwnedIPEnabled = nil
		}
		if elem.DBClusterIdentifier != nil {
			ko.Spec.DBClusterIdentifier = elem.DBClusterIdentifier
		} else {
			ko.Spec.DBClusterIdentifier = nil
		}
		if elem.DBInstanceArn != nil {
			if ko.Status.ACKResourceMetadata == nil {
				ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
			}
			tmpARN := ackv1alpha1.AWSResourceName(*elem.DBInstanceArn)
			ko.Status.ACKResourceMetadata.ARN = &tmpARN
		}
		if elem.DBInstanceAutomatedBackupsReplications != nil {
			f20 := []*svcapitypes.DBInstanceAutomatedBackupsReplication{}
			for _, f20iter := range elem.DBInstanceAutomatedBackupsReplications {
				f20elem := &svcapitypes.DBInstanceAutomatedBackupsReplication{}
				if f20iter.DBInstanceAutomatedBackupsArn != nil {
					f20elem.DBInstanceAutomatedBackupsARN = f20iter.DBInstanceAutomatedBackupsArn
				}
				f20 = append(f20, f20elem)
			}
			ko.Status.DBInstanceAutomatedBackupsReplications = f20
		} else {
			ko.Status.DBInstanceAutomatedBackupsReplications = nil
		}
		if elem.DBInstanceClass != nil {
			ko.Spec.DBInstanceClass = elem.DBInstanceClass
		} else {
			ko.Spec.DBInstanceClass = nil
		}
		if elem.DBInstanceIdentifier != nil {
			ko.Spec.DBInstanceIdentifier = elem.DBInstanceIdentifier
		} else {
			ko.Spec.DBInstanceIdentifier = nil
		}
		if elem.DBInstanceStatus != nil {
			ko.Status.DBInstanceStatus = elem.DBInstanceStatus
		} else {
			ko.Status.DBInstanceStatus = nil
		}
		if elem.DBName != nil {
			ko.Spec.DBName = elem.DBName
		} else {
			ko.Spec.DBName = nil
		}
		if elem.DBParameterGroups != nil {
			f25 := []*svcapitypes.DBParameterGroupStatus_SDK{}
			for _, f25iter := range elem.DBParameterGroups {
				f25elem := &svcapitypes.DBParameterGroupStatus_SDK{}
				if f25iter.DBParameterGroupName != nil {
					f25elem.DBParameterGroupName = f25iter.DBParameterGroupName
				}
				if f25iter.ParameterApplyStatus != nil {
					f25elem.ParameterApplyStatus = f25iter.ParameterApplyStatus
				}
				f25 = append(f25, f25elem)
			}
			ko.Status.DBParameterGroups = f25
		} else {
			ko.Status.DBParameterGroups = nil
		}
		if elem.DBSecurityGroups != nil {
			f26 := []*string{}
			for _, f26iter := range elem.DBSecurityGroups {
				var f26elem string
				f26elem = *f26iter.DBSecurityGroupName
				f26 = append(f26, &f26elem)
			}
			ko.Spec.DBSecurityGroups = f26
		} else {
			ko.Spec.DBSecurityGroups = nil
		}
		if elem.DBSubnetGroup != nil {
			f27 := &svcapitypes.DBSubnetGroup_SDK{}
			if elem.DBSubnetGroup.DBSubnetGroupArn != nil {
				f27.DBSubnetGroupARN = elem.DBSubnetGroup.DBSubnetGroupArn
			}
			if elem.DBSubnetGroup.DBSubnetGroupDescription != nil {
				f27.DBSubnetGroupDescription = elem.DBSubnetGroup.DBSubnetGroupDescription
			}
			if elem.DBSubnetGroup.DBSubnetGroupName != nil {
				f27.DBSubnetGroupName = elem.DBSubnetGroup.DBSubnetGroupName
			}
			if elem.DBSubnetGroup.SubnetGroupStatus != nil {
				f27.SubnetGroupStatus = elem.DBSubnetGroup.SubnetGroupStatus
			}
			if elem.DBSubnetGroup.Subnets != nil {
				f27f4 := []*svcapitypes.Subnet{}
				for _, f27f4iter := range elem.DBSubnetGroup.Subnets {
					f27f4elem := &svcapitypes.Subnet{}
					if f27f4iter.SubnetAvailabilityZone != nil {
						f27f4elemf0 := &svcapitypes.AvailabilityZone{}
						if f27f4iter.SubnetAvailabilityZone.Name != nil {
							f27f4elemf0.Name = f27f4iter.SubnetAvailabilityZone.Name
						}
						f27f4elem.SubnetAvailabilityZone = f27f4elemf0
					}
					if f27f4iter.SubnetIdentifier != nil {
						f27f4elem.SubnetIdentifier = f27f4iter.SubnetIdentifier
					}
					if f27f4iter.SubnetOutpost != nil {
						f27f4elemf2 := &svcapitypes.Outpost{}
						if f27f4iter.SubnetOutpost.Arn != nil {
							f27f4elemf2.ARN = f27f4iter.SubnetOutpost.Arn
						}
						f27f4elem.SubnetOutpost = f27f4elemf2
					}
					if f27f4iter.SubnetStatus != nil {
						f27f4elem.SubnetStatus = f27f4iter.SubnetStatus
					}
					f27f4 = append(f27f4, f27f4elem)
				}
				f27.Subnets = f27f4
			}
			if elem.DBSubnetGroup.VpcId != nil {
				f27.VPCID = elem.DBSubnetGroup.VpcId
			}
			ko.Status.DBSubnetGroup = f27
		} else {
			ko.Status.DBSubnetGroup = nil
		}
		if elem.DbInstancePort != nil {
			ko.Status.DBInstancePort = elem.DbInstancePort
		} else {
			ko.Status.DBInstancePort = nil
		}
		if elem.DbiResourceId != nil {
			ko.Status.DBIResourceID = elem.DbiResourceId
		} else {
			ko.Status.DBIResourceID = nil
		}
		if elem.DeletionProtection != nil {
			ko.Spec.DeletionProtection = elem.DeletionProtection
		} else {
			ko.Spec.DeletionProtection = nil
		}
		if elem.DomainMemberships != nil {
			f31 := []*svcapitypes.DomainMembership{}
			for _, f31iter := range elem.DomainMemberships {
				f31elem := &svcapitypes.DomainMembership{}
				if f31iter.Domain != nil {
					f31elem.Domain = f31iter.Domain
				}
				if f31iter.FQDN != nil {
					f31elem.FQDN = f31iter.FQDN
				}
				if f31iter.IAMRoleName != nil {
					f31elem.IAMRoleName = f31iter.IAMRoleName
				}
				if f31iter.Status != nil {
					f31elem.Status = f31iter.Status
				}
				f31 = append(f31, f31elem)
			}
			ko.Status.DomainMemberships = f31
		} else {
			ko.Status.DomainMemberships = nil
		}
		if elem.EnabledCloudwatchLogsExports != nil {
			f32 := []*string{}
			for _, f32iter := range elem.EnabledCloudwatchLogsExports {
				var f32elem string
				f32elem = *f32iter
				f32 = append(f32, &f32elem)
			}
			ko.Status.EnabledCloudwatchLogsExports = f32
		} else {
			ko.Status.EnabledCloudwatchLogsExports = nil
		}
		if elem.Endpoint != nil {
			f33 := &svcapitypes.Endpoint{}
			if elem.Endpoint.Address != nil {
				f33.Address = elem.Endpoint.Address
			}
			if elem.Endpoint.HostedZoneId != nil {
				f33.HostedZoneID = elem.Endpoint.HostedZoneId
			}
			if elem.Endpoint.Port != nil {
				f33.Port = elem.Endpoint.Port
			}
			ko.Status.Endpoint = f33
		} else {
			ko.Status.Endpoint = nil
		}
		if elem.Engine != nil {
			ko.Spec.Engine = elem.Engine
		} else {
			ko.Spec.Engine = nil
		}
		if elem.EngineVersion != nil {
			ko.Spec.EngineVersion = elem.EngineVersion
		} else {
			ko.Spec.EngineVersion = nil
		}
		if elem.EnhancedMonitoringResourceArn != nil {
			ko.Status.EnhancedMonitoringResourceARN = elem.EnhancedMonitoringResourceArn
		} else {
			ko.Status.EnhancedMonitoringResourceARN = nil
		}
		if elem.IAMDatabaseAuthenticationEnabled != nil {
			ko.Status.IAMDatabaseAuthenticationEnabled = elem.IAMDatabaseAuthenticationEnabled
		} else {
			ko.Status.IAMDatabaseAuthenticationEnabled = nil
		}
		if elem.InstanceCreateTime != nil {
			ko.Status.InstanceCreateTime = &metav1.Time{*elem.InstanceCreateTime}
		} else {
			ko.Status.InstanceCreateTime = nil
		}
		if elem.Iops != nil {
			ko.Spec.IOPS = elem.Iops
		} else {
			ko.Spec.IOPS = nil
		}
		if elem.KmsKeyId != nil {
			ko.Spec.KMSKeyID = elem.KmsKeyId
		} else {
			ko.Spec.KMSKeyID = nil
		}
		if elem.LatestRestorableTime != nil {
			ko.Status.LatestRestorableTime = &metav1.Time{*elem.LatestRestorableTime}
		} else {
			ko.Status.LatestRestorableTime = nil
		}
		if elem.LicenseModel != nil {
			ko.Spec.LicenseModel = elem.LicenseModel
		} else {
			ko.Spec.LicenseModel = nil
		}
		if elem.ListenerEndpoint != nil {
			f43 := &svcapitypes.Endpoint{}
			if elem.ListenerEndpoint.Address != nil {
				f43.Address = elem.ListenerEndpoint.Address
			}
			if elem.ListenerEndpoint.HostedZoneId != nil {
				f43.HostedZoneID = elem.ListenerEndpoint.HostedZoneId
			}
			if elem.ListenerEndpoint.Port != nil {
				f43.Port = elem.ListenerEndpoint.Port
			}
			ko.Status.ListenerEndpoint = f43
		} else {
			ko.Status.ListenerEndpoint = nil
		}
		if elem.MasterUsername != nil {
			ko.Spec.MasterUsername = elem.MasterUsername
		} else {
			ko.Spec.MasterUsername = nil
		}
		if elem.MaxAllocatedStorage != nil {
			ko.Spec.MaxAllocatedStorage = elem.MaxAllocatedStorage
		} else {
			ko.Spec.MaxAllocatedStorage = nil
		}
		if elem.MonitoringInterval != nil {
			ko.Spec.MonitoringInterval = elem.MonitoringInterval
		} else {
			ko.Spec.MonitoringInterval = nil
		}
		if elem.MonitoringRoleArn != nil {
			ko.Spec.MonitoringRoleARN = elem.MonitoringRoleArn
		} else {
			ko.Spec.MonitoringRoleARN = nil
		}
		if elem.MultiAZ != nil {
			ko.Spec.MultiAZ = elem.MultiAZ
		} else {
			ko.Spec.MultiAZ = nil
		}
		if elem.NcharCharacterSetName != nil {
			ko.Spec.NcharCharacterSetName = elem.NcharCharacterSetName
		} else {
			ko.Spec.NcharCharacterSetName = nil
		}
		if elem.OptionGroupMemberships != nil {
			f50 := []*svcapitypes.OptionGroupMembership{}
			for _, f50iter := range elem.OptionGroupMemberships {
				f50elem := &svcapitypes.OptionGroupMembership{}
				if f50iter.OptionGroupName != nil {
					f50elem.OptionGroupName = f50iter.OptionGroupName
				}
				if f50iter.Status != nil {
					f50elem.Status = f50iter.Status
				}
				f50 = append(f50, f50elem)
			}
			ko.Status.OptionGroupMemberships = f50
		} else {
			ko.Status.OptionGroupMemberships = nil
		}
		if elem.PendingModifiedValues != nil {
			f51 := &svcapitypes.PendingModifiedValues{}
			if elem.PendingModifiedValues.AllocatedStorage != nil {
				f51.AllocatedStorage = elem.PendingModifiedValues.AllocatedStorage
			}
			if elem.PendingModifiedValues.AutomationMode != nil {
				f51.AutomationMode = elem.PendingModifiedValues.AutomationMode
			}
			if elem.PendingModifiedValues.BackupRetentionPeriod != nil {
				f51.BackupRetentionPeriod = elem.PendingModifiedValues.BackupRetentionPeriod
			}
			if elem.PendingModifiedValues.CACertificateIdentifier != nil {
				f51.CACertificateIdentifier = elem.PendingModifiedValues.CACertificateIdentifier
			}
			if elem.PendingModifiedValues.DBInstanceClass != nil {
				f51.DBInstanceClass = elem.PendingModifiedValues.DBInstanceClass
			}
			if elem.PendingModifiedValues.DBInstanceIdentifier != nil {
				f51.DBInstanceIdentifier = elem.PendingModifiedValues.DBInstanceIdentifier
			}
			if elem.PendingModifiedValues.DBSubnetGroupName != nil {
				f51.DBSubnetGroupName = elem.PendingModifiedValues.DBSubnetGroupName
			}
			if elem.PendingModifiedValues.EngineVersion != nil {
				f51.EngineVersion = elem.PendingModifiedValues.EngineVersion
			}
			if elem.PendingModifiedValues.IAMDatabaseAuthenticationEnabled != nil {
				f51.IAMDatabaseAuthenticationEnabled = elem.PendingModifiedValues.IAMDatabaseAuthenticationEnabled
			}
			if elem.PendingModifiedValues.Iops != nil {
				f51.IOPS = elem.PendingModifiedValues.Iops
			}
			if elem.PendingModifiedValues.LicenseModel != nil {
				f51.LicenseModel = elem.PendingModifiedValues.LicenseModel
			}
			if elem.PendingModifiedValues.MasterUserPassword != nil {
				f51.MasterUserPassword = elem.PendingModifiedValues.MasterUserPassword
			}
			if elem.PendingModifiedValues.MultiAZ != nil {
				f51.MultiAZ = elem.PendingModifiedValues.MultiAZ
			}
			if elem.PendingModifiedValues.PendingCloudwatchLogsExports != nil {
				f51f13 := &svcapitypes.PendingCloudwatchLogsExports{}
				if elem.PendingModifiedValues.PendingCloudwatchLogsExports.LogTypesToDisable != nil {
					f51f13f0 := []*string{}
					for _, f51f13f0iter := range elem.PendingModifiedValues.PendingCloudwatchLogsExports.LogTypesToDisable {
						var f51f13f0elem string
						f51f13f0elem = *f51f13f0iter
						f51f13f0 = append(f51f13f0, &f51f13f0elem)
					}
					f51f13.LogTypesToDisable = f51f13f0
				}
				if elem.PendingModifiedValues.PendingCloudwatchLogsExports.LogTypesToEnable != nil {
					f51f13f1 := []*string{}
					for _, f51f13f1iter := range elem.PendingModifiedValues.PendingCloudwatchLogsExports.LogTypesToEnable {
						var f51f13f1elem string
						f51f13f1elem = *f51f13f1iter
						f51f13f1 = append(f51f13f1, &f51f13f1elem)
					}
					f51f13.LogTypesToEnable = f51f13f1
				}
				f51.PendingCloudwatchLogsExports = f51f13
			}
			if elem.PendingModifiedValues.Port != nil {
				f51.Port = elem.PendingModifiedValues.Port
			}
			if elem.PendingModifiedValues.ProcessorFeatures != nil {
				f51f15 := []*svcapitypes.ProcessorFeature{}
				for _, f51f15iter := range elem.PendingModifiedValues.ProcessorFeatures {
					f51f15elem := &svcapitypes.ProcessorFeature{}
					if f51f15iter.Name != nil {
						f51f15elem.Name = f51f15iter.Name
					}
					if f51f15iter.Value != nil {
						f51f15elem.Value = f51f15iter.Value
					}
					f51f15 = append(f51f15, f51f15elem)
				}
				f51.ProcessorFeatures = f51f15
			}
			if elem.PendingModifiedValues.ResumeFullAutomationModeTime != nil {
				f51.ResumeFullAutomationModeTime = &metav1.Time{*elem.PendingModifiedValues.ResumeFullAutomationModeTime}
			}
			if elem.PendingModifiedValues.StorageType != nil {
				f51.StorageType = elem.PendingModifiedValues.StorageType
			}
			ko.Status.PendingModifiedValues = f51
		} else {
			ko.Status.PendingModifiedValues = nil
		}
		if elem.PerformanceInsightsEnabled != nil {
			ko.Status.PerformanceInsightsEnabled = elem.PerformanceInsightsEnabled
		} else {
			ko.Status.PerformanceInsightsEnabled = nil
		}
		if elem.PerformanceInsightsKMSKeyId != nil {
			ko.Spec.PerformanceInsightsKMSKeyID = elem.PerformanceInsightsKMSKeyId
		} else {
			ko.Spec.PerformanceInsightsKMSKeyID = nil
		}
		if elem.PerformanceInsightsRetentionPeriod != nil {
			ko.Spec.PerformanceInsightsRetentionPeriod = elem.PerformanceInsightsRetentionPeriod
		} else {
			ko.Spec.PerformanceInsightsRetentionPeriod = nil
		}
		if elem.PreferredBackupWindow != nil {
			ko.Spec.PreferredBackupWindow = elem.PreferredBackupWindow
		} else {
			ko.Spec.PreferredBackupWindow = nil
		}
		if elem.PreferredMaintenanceWindow != nil {
			ko.Spec.PreferredMaintenanceWindow = elem.PreferredMaintenanceWindow
		} else {
			ko.Spec.PreferredMaintenanceWindow = nil
		}
		if elem.ProcessorFeatures != nil {
			f57 := []*svcapitypes.ProcessorFeature{}
			for _, f57iter := range elem.ProcessorFeatures {
				f57elem := &svcapitypes.ProcessorFeature{}
				if f57iter.Name != nil {
					f57elem.Name = f57iter.Name
				}
				if f57iter.Value != nil {
					f57elem.Value = f57iter.Value
				}
				f57 = append(f57, f57elem)
			}
			ko.Spec.ProcessorFeatures = f57
		} else {
			ko.Spec.ProcessorFeatures = nil
		}
		if elem.PromotionTier != nil {
			ko.Spec.PromotionTier = elem.PromotionTier
		} else {
			ko.Spec.PromotionTier = nil
		}
		if elem.PubliclyAccessible != nil {
			ko.Spec.PubliclyAccessible = elem.PubliclyAccessible
		} else {
			ko.Spec.PubliclyAccessible = nil
		}
		if elem.ReadReplicaDBClusterIdentifiers != nil {
			f60 := []*string{}
			for _, f60iter := range elem.ReadReplicaDBClusterIdentifiers {
				var f60elem string
				f60elem = *f60iter
				f60 = append(f60, &f60elem)
			}
			ko.Status.ReadReplicaDBClusterIdentifiers = f60
		} else {
			ko.Status.ReadReplicaDBClusterIdentifiers = nil
		}
		if elem.ReadReplicaDBInstanceIdentifiers != nil {
			f61 := []*string{}
			for _, f61iter := range elem.ReadReplicaDBInstanceIdentifiers {
				var f61elem string
				f61elem = *f61iter
				f61 = append(f61, &f61elem)
			}
			ko.Status.ReadReplicaDBInstanceIdentifiers = f61
		} else {
			ko.Status.ReadReplicaDBInstanceIdentifiers = nil
		}
		if elem.ReadReplicaSourceDBInstanceIdentifier != nil {
			ko.Status.ReadReplicaSourceDBInstanceIdentifier = elem.ReadReplicaSourceDBInstanceIdentifier
		} else {
			ko.Status.ReadReplicaSourceDBInstanceIdentifier = nil
		}
		if elem.ReplicaMode != nil {
			ko.Status.ReplicaMode = elem.ReplicaMode
		} else {
			ko.Status.ReplicaMode = nil
		}
		if elem.ResumeFullAutomationModeTime != nil {
			ko.Status.ResumeFullAutomationModeTime = &metav1.Time{*elem.ResumeFullAutomationModeTime}
		} else {
			ko.Status.ResumeFullAutomationModeTime = nil
		}
		if elem.SecondaryAvailabilityZone != nil {
			ko.Status.SecondaryAvailabilityZone = elem.SecondaryAvailabilityZone
		} else {
			ko.Status.SecondaryAvailabilityZone = nil
		}
		if elem.StatusInfos != nil {
			f66 := []*svcapitypes.DBInstanceStatusInfo{}
			for _, f66iter := range elem.StatusInfos {
				f66elem := &svcapitypes.DBInstanceStatusInfo{}
				if f66iter.Message != nil {
					f66elem.Message = f66iter.Message
				}
				if f66iter.Normal != nil {
					f66elem.Normal = f66iter.Normal
				}
				if f66iter.Status != nil {
					f66elem.Status = f66iter.Status
				}
				if f66iter.StatusType != nil {
					f66elem.StatusType = f66iter.StatusType
				}
				f66 = append(f66, f66elem)
			}
			ko.Status.StatusInfos = f66
		} else {
			ko.Status.StatusInfos = nil
		}
		if elem.StorageEncrypted != nil {
			ko.Spec.StorageEncrypted = elem.StorageEncrypted
		} else {
			ko.Spec.StorageEncrypted = nil
		}
		if elem.StorageType != nil {
			ko.Spec.StorageType = elem.StorageType
		} else {
			ko.Spec.StorageType = nil
		}
		if elem.TagList != nil {
			f69 := []*svcapitypes.Tag{}
			for _, f69iter := range elem.TagList {
				f69elem := &svcapitypes.Tag{}
				if f69iter.Key != nil {
					f69elem.Key = f69iter.Key
				}
				if f69iter.Value != nil {
					f69elem.Value = f69iter.Value
				}
				f69 = append(f69, f69elem)
			}
			ko.Status.TagList = f69
		} else {
			ko.Status.TagList = nil
		}
		if elem.TdeCredentialArn != nil {
			ko.Spec.TDECredentialARN = elem.TdeCredentialArn
		} else {
			ko.Spec.TDECredentialARN = nil
		}
		if elem.Timezone != nil {
			ko.Spec.Timezone = elem.Timezone
		} else {
			ko.Spec.Timezone = nil
		}
		if elem.VpcSecurityGroups != nil {
			f72 := []*svcapitypes.VPCSecurityGroupMembership{}
			for _, f72iter := range elem.VpcSecurityGroups {
				f72elem := &svcapitypes.VPCSecurityGroupMembership{}
				if f72iter.Status != nil {
					f72elem.Status = f72iter.Status
				}
				if f72iter.VpcSecurityGroupId != nil {
					f72elem.VPCSecurityGroupID = f72iter.VpcSecurityGroupId
				}
				f72 = append(f72, f72elem)
			}
			ko.Status.VPCSecurityGroups = f72
		} else {
			ko.Status.VPCSecurityGroups = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)
	if !instanceAvailable(&resource{ko}) {
		// Setting resource synced condition to false will trigger a requeue of
		// the resource. No need to return a requeue error here.
		ackcondition.SetSynced(&resource{ko}, corev1.ConditionFalse, nil, nil)
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadManyInput returns true if there are any fields
// for the ReadMany Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadManyInput(
	r *resource,
) bool {
	return false
}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeDBInstancesInput, error) {
	res := &svcsdk.DescribeDBInstancesInput{}

	if r.ko.Spec.DBInstanceIdentifier != nil {
		res.SetDBInstanceIdentifier(*r.ko.Spec.DBInstanceIdentifier)
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer exit(err)
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateDBInstanceOutput
	_ = resp
	resp, err = rm.sdkapi.CreateDBInstanceWithContext(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateDBInstance", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.DBInstance.ActivityStreamEngineNativeAuditFieldsIncluded != nil {
		ko.Status.ActivityStreamEngineNativeAuditFieldsIncluded = resp.DBInstance.ActivityStreamEngineNativeAuditFieldsIncluded
	} else {
		ko.Status.ActivityStreamEngineNativeAuditFieldsIncluded = nil
	}
	if resp.DBInstance.ActivityStreamKinesisStreamName != nil {
		ko.Status.ActivityStreamKinesisStreamName = resp.DBInstance.ActivityStreamKinesisStreamName
	} else {
		ko.Status.ActivityStreamKinesisStreamName = nil
	}
	if resp.DBInstance.ActivityStreamKmsKeyId != nil {
		ko.Status.ActivityStreamKMSKeyID = resp.DBInstance.ActivityStreamKmsKeyId
	} else {
		ko.Status.ActivityStreamKMSKeyID = nil
	}
	if resp.DBInstance.ActivityStreamMode != nil {
		ko.Status.ActivityStreamMode = resp.DBInstance.ActivityStreamMode
	} else {
		ko.Status.ActivityStreamMode = nil
	}
	if resp.DBInstance.ActivityStreamStatus != nil {
		ko.Status.ActivityStreamStatus = resp.DBInstance.ActivityStreamStatus
	} else {
		ko.Status.ActivityStreamStatus = nil
	}
	if resp.DBInstance.AllocatedStorage != nil {
		ko.Spec.AllocatedStorage = resp.DBInstance.AllocatedStorage
	} else {
		ko.Spec.AllocatedStorage = nil
	}
	if resp.DBInstance.AssociatedRoles != nil {
		f6 := []*svcapitypes.DBInstanceRole{}
		for _, f6iter := range resp.DBInstance.AssociatedRoles {
			f6elem := &svcapitypes.DBInstanceRole{}
			if f6iter.FeatureName != nil {
				f6elem.FeatureName = f6iter.FeatureName
			}
			if f6iter.RoleArn != nil {
				f6elem.RoleARN = f6iter.RoleArn
			}
			if f6iter.Status != nil {
				f6elem.Status = f6iter.Status
			}
			f6 = append(f6, f6elem)
		}
		ko.Status.AssociatedRoles = f6
	} else {
		ko.Status.AssociatedRoles = nil
	}
	if resp.DBInstance.AutoMinorVersionUpgrade != nil {
		ko.Spec.AutoMinorVersionUpgrade = resp.DBInstance.AutoMinorVersionUpgrade
	} else {
		ko.Spec.AutoMinorVersionUpgrade = nil
	}
	if resp.DBInstance.AutomaticRestartTime != nil {
		ko.Status.AutomaticRestartTime = &metav1.Time{*resp.DBInstance.AutomaticRestartTime}
	} else {
		ko.Status.AutomaticRestartTime = nil
	}
	if resp.DBInstance.AutomationMode != nil {
		ko.Status.AutomationMode = resp.DBInstance.AutomationMode
	} else {
		ko.Status.AutomationMode = nil
	}
	if resp.DBInstance.AvailabilityZone != nil {
		ko.Spec.AvailabilityZone = resp.DBInstance.AvailabilityZone
	} else {
		ko.Spec.AvailabilityZone = nil
	}
	if resp.DBInstance.AwsBackupRecoveryPointArn != nil {
		ko.Status.AWSBackupRecoveryPointARN = resp.DBInstance.AwsBackupRecoveryPointArn
	} else {
		ko.Status.AWSBackupRecoveryPointARN = nil
	}
	if resp.DBInstance.BackupRetentionPeriod != nil {
		ko.Spec.BackupRetentionPeriod = resp.DBInstance.BackupRetentionPeriod
	} else {
		ko.Spec.BackupRetentionPeriod = nil
	}
	if resp.DBInstance.CACertificateIdentifier != nil {
		ko.Status.CACertificateIdentifier = resp.DBInstance.CACertificateIdentifier
	} else {
		ko.Status.CACertificateIdentifier = nil
	}
	if resp.DBInstance.CharacterSetName != nil {
		ko.Spec.CharacterSetName = resp.DBInstance.CharacterSetName
	} else {
		ko.Spec.CharacterSetName = nil
	}
	if resp.DBInstance.CopyTagsToSnapshot != nil {
		ko.Spec.CopyTagsToSnapshot = resp.DBInstance.CopyTagsToSnapshot
	} else {
		ko.Spec.CopyTagsToSnapshot = nil
	}
	if resp.DBInstance.CustomIamInstanceProfile != nil {
		ko.Spec.CustomIAMInstanceProfile = resp.DBInstance.CustomIamInstanceProfile
	} else {
		ko.Spec.CustomIAMInstanceProfile = nil
	}
	if resp.DBInstance.CustomerOwnedIpEnabled != nil {
		ko.Status.CustomerOwnedIPEnabled = resp.DBInstance.CustomerOwnedIpEnabled
	} else {
		ko.Status.CustomerOwnedIPEnabled = nil
	}
	if resp.DBInstance.DBClusterIdentifier != nil {
		ko.Spec.DBClusterIdentifier = resp.DBInstance.DBClusterIdentifier
	} else {
		ko.Spec.DBClusterIdentifier = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.DBInstance.DBInstanceArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.DBInstance.DBInstanceArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.DBInstance.DBInstanceAutomatedBackupsReplications != nil {
		f20 := []*svcapitypes.DBInstanceAutomatedBackupsReplication{}
		for _, f20iter := range resp.DBInstance.DBInstanceAutomatedBackupsReplications {
			f20elem := &svcapitypes.DBInstanceAutomatedBackupsReplication{}
			if f20iter.DBInstanceAutomatedBackupsArn != nil {
				f20elem.DBInstanceAutomatedBackupsARN = f20iter.DBInstanceAutomatedBackupsArn
			}
			f20 = append(f20, f20elem)
		}
		ko.Status.DBInstanceAutomatedBackupsReplications = f20
	} else {
		ko.Status.DBInstanceAutomatedBackupsReplications = nil
	}
	if resp.DBInstance.DBInstanceClass != nil {
		ko.Spec.DBInstanceClass = resp.DBInstance.DBInstanceClass
	} else {
		ko.Spec.DBInstanceClass = nil
	}
	if resp.DBInstance.DBInstanceIdentifier != nil {
		ko.Spec.DBInstanceIdentifier = resp.DBInstance.DBInstanceIdentifier
	} else {
		ko.Spec.DBInstanceIdentifier = nil
	}
	if resp.DBInstance.DBInstanceStatus != nil {
		ko.Status.DBInstanceStatus = resp.DBInstance.DBInstanceStatus
	} else {
		ko.Status.DBInstanceStatus = nil
	}
	if resp.DBInstance.DBName != nil {
		ko.Spec.DBName = resp.DBInstance.DBName
	} else {
		ko.Spec.DBName = nil
	}
	if resp.DBInstance.DBParameterGroups != nil {
		f25 := []*svcapitypes.DBParameterGroupStatus_SDK{}
		for _, f25iter := range resp.DBInstance.DBParameterGroups {
			f25elem := &svcapitypes.DBParameterGroupStatus_SDK{}
			if f25iter.DBParameterGroupName != nil {
				f25elem.DBParameterGroupName = f25iter.DBParameterGroupName
			}
			if f25iter.ParameterApplyStatus != nil {
				f25elem.ParameterApplyStatus = f25iter.ParameterApplyStatus
			}
			f25 = append(f25, f25elem)
		}
		ko.Status.DBParameterGroups = f25
	} else {
		ko.Status.DBParameterGroups = nil
	}
	if resp.DBInstance.DBSecurityGroups != nil {
		f26 := []*string{}
		for _, f26iter := range resp.DBInstance.DBSecurityGroups {
			var f26elem string
			f26elem = *f26iter.DBSecurityGroupName
			f26 = append(f26, &f26elem)
		}
		ko.Spec.DBSecurityGroups = f26
	} else {
		ko.Spec.DBSecurityGroups = nil
	}
	if resp.DBInstance.DBSubnetGroup != nil {
		f27 := &svcapitypes.DBSubnetGroup_SDK{}
		if resp.DBInstance.DBSubnetGroup.DBSubnetGroupArn != nil {
			f27.DBSubnetGroupARN = resp.DBInstance.DBSubnetGroup.DBSubnetGroupArn
		}
		if resp.DBInstance.DBSubnetGroup.DBSubnetGroupDescription != nil {
			f27.DBSubnetGroupDescription = resp.DBInstance.DBSubnetGroup.DBSubnetGroupDescription
		}
		if resp.DBInstance.DBSubnetGroup.DBSubnetGroupName != nil {
			f27.DBSubnetGroupName = resp.DBInstance.DBSubnetGroup.DBSubnetGroupName
		}
		if resp.DBInstance.DBSubnetGroup.SubnetGroupStatus != nil {
			f27.SubnetGroupStatus = resp.DBInstance.DBSubnetGroup.SubnetGroupStatus
		}
		if resp.DBInstance.DBSubnetGroup.Subnets != nil {
			f27f4 := []*svcapitypes.Subnet{}
			for _, f27f4iter := range resp.DBInstance.DBSubnetGroup.Subnets {
				f27f4elem := &svcapitypes.Subnet{}
				if f27f4iter.SubnetAvailabilityZone != nil {
					f27f4elemf0 := &svcapitypes.AvailabilityZone{}
					if f27f4iter.SubnetAvailabilityZone.Name != nil {
						f27f4elemf0.Name = f27f4iter.SubnetAvailabilityZone.Name
					}
					f27f4elem.SubnetAvailabilityZone = f27f4elemf0
				}
				if f27f4iter.SubnetIdentifier != nil {
					f27f4elem.SubnetIdentifier = f27f4iter.SubnetIdentifier
				}
				if f27f4iter.SubnetOutpost != nil {
					f27f4elemf2 := &svcapitypes.Outpost{}
					if f27f4iter.SubnetOutpost.Arn != nil {
						f27f4elemf2.ARN = f27f4iter.SubnetOutpost.Arn
					}
					f27f4elem.SubnetOutpost = f27f4elemf2
				}
				if f27f4iter.SubnetStatus != nil {
					f27f4elem.SubnetStatus = f27f4iter.SubnetStatus
				}
				f27f4 = append(f27f4, f27f4elem)
			}
			f27.Subnets = f27f4
		}
		if resp.DBInstance.DBSubnetGroup.VpcId != nil {
			f27.VPCID = resp.DBInstance.DBSubnetGroup.VpcId
		}
		ko.Status.DBSubnetGroup = f27
	} else {
		ko.Status.DBSubnetGroup = nil
	}
	if resp.DBInstance.DbInstancePort != nil {
		ko.Status.DBInstancePort = resp.DBInstance.DbInstancePort
	} else {
		ko.Status.DBInstancePort = nil
	}
	if resp.DBInstance.DbiResourceId != nil {
		ko.Status.DBIResourceID = resp.DBInstance.DbiResourceId
	} else {
		ko.Status.DBIResourceID = nil
	}
	if resp.DBInstance.DeletionProtection != nil {
		ko.Spec.DeletionProtection = resp.DBInstance.DeletionProtection
	} else {
		ko.Spec.DeletionProtection = nil
	}
	if resp.DBInstance.DomainMemberships != nil {
		f31 := []*svcapitypes.DomainMembership{}
		for _, f31iter := range resp.DBInstance.DomainMemberships {
			f31elem := &svcapitypes.DomainMembership{}
			if f31iter.Domain != nil {
				f31elem.Domain = f31iter.Domain
			}
			if f31iter.FQDN != nil {
				f31elem.FQDN = f31iter.FQDN
			}
			if f31iter.IAMRoleName != nil {
				f31elem.IAMRoleName = f31iter.IAMRoleName
			}
			if f31iter.Status != nil {
				f31elem.Status = f31iter.Status
			}
			f31 = append(f31, f31elem)
		}
		ko.Status.DomainMemberships = f31
	} else {
		ko.Status.DomainMemberships = nil
	}
	if resp.DBInstance.EnabledCloudwatchLogsExports != nil {
		f32 := []*string{}
		for _, f32iter := range resp.DBInstance.EnabledCloudwatchLogsExports {
			var f32elem string
			f32elem = *f32iter
			f32 = append(f32, &f32elem)
		}
		ko.Status.EnabledCloudwatchLogsExports = f32
	} else {
		ko.Status.EnabledCloudwatchLogsExports = nil
	}
	if resp.DBInstance.Endpoint != nil {
		f33 := &svcapitypes.Endpoint{}
		if resp.DBInstance.Endpoint.Address != nil {
			f33.Address = resp.DBInstance.Endpoint.Address
		}
		if resp.DBInstance.Endpoint.HostedZoneId != nil {
			f33.HostedZoneID = resp.DBInstance.Endpoint.HostedZoneId
		}
		if resp.DBInstance.Endpoint.Port != nil {
			f33.Port = resp.DBInstance.Endpoint.Port
		}
		ko.Status.Endpoint = f33
	} else {
		ko.Status.Endpoint = nil
	}
	if resp.DBInstance.Engine != nil {
		ko.Spec.Engine = resp.DBInstance.Engine
	} else {
		ko.Spec.Engine = nil
	}
	if resp.DBInstance.EngineVersion != nil {
		ko.Spec.EngineVersion = resp.DBInstance.EngineVersion
	} else {
		ko.Spec.EngineVersion = nil
	}
	if resp.DBInstance.EnhancedMonitoringResourceArn != nil {
		ko.Status.EnhancedMonitoringResourceARN = resp.DBInstance.EnhancedMonitoringResourceArn
	} else {
		ko.Status.EnhancedMonitoringResourceARN = nil
	}
	if resp.DBInstance.IAMDatabaseAuthenticationEnabled != nil {
		ko.Status.IAMDatabaseAuthenticationEnabled = resp.DBInstance.IAMDatabaseAuthenticationEnabled
	} else {
		ko.Status.IAMDatabaseAuthenticationEnabled = nil
	}
	if resp.DBInstance.InstanceCreateTime != nil {
		ko.Status.InstanceCreateTime = &metav1.Time{*resp.DBInstance.InstanceCreateTime}
	} else {
		ko.Status.InstanceCreateTime = nil
	}
	if resp.DBInstance.Iops != nil {
		ko.Spec.IOPS = resp.DBInstance.Iops
	} else {
		ko.Spec.IOPS = nil
	}
	if resp.DBInstance.KmsKeyId != nil {
		ko.Spec.KMSKeyID = resp.DBInstance.KmsKeyId
	} else {
		ko.Spec.KMSKeyID = nil
	}
	if resp.DBInstance.LatestRestorableTime != nil {
		ko.Status.LatestRestorableTime = &metav1.Time{*resp.DBInstance.LatestRestorableTime}
	} else {
		ko.Status.LatestRestorableTime = nil
	}
	if resp.DBInstance.LicenseModel != nil {
		ko.Spec.LicenseModel = resp.DBInstance.LicenseModel
	} else {
		ko.Spec.LicenseModel = nil
	}
	if resp.DBInstance.ListenerEndpoint != nil {
		f43 := &svcapitypes.Endpoint{}
		if resp.DBInstance.ListenerEndpoint.Address != nil {
			f43.Address = resp.DBInstance.ListenerEndpoint.Address
		}
		if resp.DBInstance.ListenerEndpoint.HostedZoneId != nil {
			f43.HostedZoneID = resp.DBInstance.ListenerEndpoint.HostedZoneId
		}
		if resp.DBInstance.ListenerEndpoint.Port != nil {
			f43.Port = resp.DBInstance.ListenerEndpoint.Port
		}
		ko.Status.ListenerEndpoint = f43
	} else {
		ko.Status.ListenerEndpoint = nil
	}
	if resp.DBInstance.MasterUsername != nil {
		ko.Spec.MasterUsername = resp.DBInstance.MasterUsername
	} else {
		ko.Spec.MasterUsername = nil
	}
	if resp.DBInstance.MaxAllocatedStorage != nil {
		ko.Spec.MaxAllocatedStorage = resp.DBInstance.MaxAllocatedStorage
	} else {
		ko.Spec.MaxAllocatedStorage = nil
	}
	if resp.DBInstance.MonitoringInterval != nil {
		ko.Spec.MonitoringInterval = resp.DBInstance.MonitoringInterval
	} else {
		ko.Spec.MonitoringInterval = nil
	}
	if resp.DBInstance.MonitoringRoleArn != nil {
		ko.Spec.MonitoringRoleARN = resp.DBInstance.MonitoringRoleArn
	} else {
		ko.Spec.MonitoringRoleARN = nil
	}
	if resp.DBInstance.MultiAZ != nil {
		ko.Spec.MultiAZ = resp.DBInstance.MultiAZ
	} else {
		ko.Spec.MultiAZ = nil
	}
	if resp.DBInstance.NcharCharacterSetName != nil {
		ko.Spec.NcharCharacterSetName = resp.DBInstance.NcharCharacterSetName
	} else {
		ko.Spec.NcharCharacterSetName = nil
	}
	if resp.DBInstance.OptionGroupMemberships != nil {
		f50 := []*svcapitypes.OptionGroupMembership{}
		for _, f50iter := range resp.DBInstance.OptionGroupMemberships {
			f50elem := &svcapitypes.OptionGroupMembership{}
			if f50iter.OptionGroupName != nil {
				f50elem.OptionGroupName = f50iter.OptionGroupName
			}
			if f50iter.Status != nil {
				f50elem.Status = f50iter.Status
			}
			f50 = append(f50, f50elem)
		}
		ko.Status.OptionGroupMemberships = f50
	} else {
		ko.Status.OptionGroupMemberships = nil
	}
	if resp.DBInstance.PendingModifiedValues != nil {
		f51 := &svcapitypes.PendingModifiedValues{}
		if resp.DBInstance.PendingModifiedValues.AllocatedStorage != nil {
			f51.AllocatedStorage = resp.DBInstance.PendingModifiedValues.AllocatedStorage
		}
		if resp.DBInstance.PendingModifiedValues.AutomationMode != nil {
			f51.AutomationMode = resp.DBInstance.PendingModifiedValues.AutomationMode
		}
		if resp.DBInstance.PendingModifiedValues.BackupRetentionPeriod != nil {
			f51.BackupRetentionPeriod = resp.DBInstance.PendingModifiedValues.BackupRetentionPeriod
		}
		if resp.DBInstance.PendingModifiedValues.CACertificateIdentifier != nil {
			f51.CACertificateIdentifier = resp.DBInstance.PendingModifiedValues.CACertificateIdentifier
		}
		if resp.DBInstance.PendingModifiedValues.DBInstanceClass != nil {
			f51.DBInstanceClass = resp.DBInstance.PendingModifiedValues.DBInstanceClass
		}
		if resp.DBInstance.PendingModifiedValues.DBInstanceIdentifier != nil {
			f51.DBInstanceIdentifier = resp.DBInstance.PendingModifiedValues.DBInstanceIdentifier
		}
		if resp.DBInstance.PendingModifiedValues.DBSubnetGroupName != nil {
			f51.DBSubnetGroupName = resp.DBInstance.PendingModifiedValues.DBSubnetGroupName
		}
		if resp.DBInstance.PendingModifiedValues.EngineVersion != nil {
			f51.EngineVersion = resp.DBInstance.PendingModifiedValues.EngineVersion
		}
		if resp.DBInstance.PendingModifiedValues.IAMDatabaseAuthenticationEnabled != nil {
			f51.IAMDatabaseAuthenticationEnabled = resp.DBInstance.PendingModifiedValues.IAMDatabaseAuthenticationEnabled
		}
		if resp.DBInstance.PendingModifiedValues.Iops != nil {
			f51.IOPS = resp.DBInstance.PendingModifiedValues.Iops
		}
		if resp.DBInstance.PendingModifiedValues.LicenseModel != nil {
			f51.LicenseModel = resp.DBInstance.PendingModifiedValues.LicenseModel
		}
		if resp.DBInstance.PendingModifiedValues.MasterUserPassword != nil {
			f51.MasterUserPassword = resp.DBInstance.PendingModifiedValues.MasterUserPassword
		}
		if resp.DBInstance.PendingModifiedValues.MultiAZ != nil {
			f51.MultiAZ = resp.DBInstance.PendingModifiedValues.MultiAZ
		}
		if resp.DBInstance.PendingModifiedValues.PendingCloudwatchLogsExports != nil {
			f51f13 := &svcapitypes.PendingCloudwatchLogsExports{}
			if resp.DBInstance.PendingModifiedValues.PendingCloudwatchLogsExports.LogTypesToDisable != nil {
				f51f13f0 := []*string{}
				for _, f51f13f0iter := range resp.DBInstance.PendingModifiedValues.PendingCloudwatchLogsExports.LogTypesToDisable {
					var f51f13f0elem string
					f51f13f0elem = *f51f13f0iter
					f51f13f0 = append(f51f13f0, &f51f13f0elem)
				}
				f51f13.LogTypesToDisable = f51f13f0
			}
			if resp.DBInstance.PendingModifiedValues.PendingCloudwatchLogsExports.LogTypesToEnable != nil {
				f51f13f1 := []*string{}
				for _, f51f13f1iter := range resp.DBInstance.PendingModifiedValues.PendingCloudwatchLogsExports.LogTypesToEnable {
					var f51f13f1elem string
					f51f13f1elem = *f51f13f1iter
					f51f13f1 = append(f51f13f1, &f51f13f1elem)
				}
				f51f13.LogTypesToEnable = f51f13f1
			}
			f51.PendingCloudwatchLogsExports = f51f13
		}
		if resp.DBInstance.PendingModifiedValues.Port != nil {
			f51.Port = resp.DBInstance.PendingModifiedValues.Port
		}
		if resp.DBInstance.PendingModifiedValues.ProcessorFeatures != nil {
			f51f15 := []*svcapitypes.ProcessorFeature{}
			for _, f51f15iter := range resp.DBInstance.PendingModifiedValues.ProcessorFeatures {
				f51f15elem := &svcapitypes.ProcessorFeature{}
				if f51f15iter.Name != nil {
					f51f15elem.Name = f51f15iter.Name
				}
				if f51f15iter.Value != nil {
					f51f15elem.Value = f51f15iter.Value
				}
				f51f15 = append(f51f15, f51f15elem)
			}
			f51.ProcessorFeatures = f51f15
		}
		if resp.DBInstance.PendingModifiedValues.ResumeFullAutomationModeTime != nil {
			f51.ResumeFullAutomationModeTime = &metav1.Time{*resp.DBInstance.PendingModifiedValues.ResumeFullAutomationModeTime}
		}
		if resp.DBInstance.PendingModifiedValues.StorageType != nil {
			f51.StorageType = resp.DBInstance.PendingModifiedValues.StorageType
		}
		ko.Status.PendingModifiedValues = f51
	} else {
		ko.Status.PendingModifiedValues = nil
	}
	if resp.DBInstance.PerformanceInsightsEnabled != nil {
		ko.Status.PerformanceInsightsEnabled = resp.DBInstance.PerformanceInsightsEnabled
	} else {
		ko.Status.PerformanceInsightsEnabled = nil
	}
	if resp.DBInstance.PerformanceInsightsKMSKeyId != nil {
		ko.Spec.PerformanceInsightsKMSKeyID = resp.DBInstance.PerformanceInsightsKMSKeyId
	} else {
		ko.Spec.PerformanceInsightsKMSKeyID = nil
	}
	if resp.DBInstance.PerformanceInsightsRetentionPeriod != nil {
		ko.Spec.PerformanceInsightsRetentionPeriod = resp.DBInstance.PerformanceInsightsRetentionPeriod
	} else {
		ko.Spec.PerformanceInsightsRetentionPeriod = nil
	}
	if resp.DBInstance.PreferredBackupWindow != nil {
		ko.Spec.PreferredBackupWindow = resp.DBInstance.PreferredBackupWindow
	} else {
		ko.Spec.PreferredBackupWindow = nil
	}
	if resp.DBInstance.PreferredMaintenanceWindow != nil {
		ko.Spec.PreferredMaintenanceWindow = resp.DBInstance.PreferredMaintenanceWindow
	} else {
		ko.Spec.PreferredMaintenanceWindow = nil
	}
	if resp.DBInstance.ProcessorFeatures != nil {
		f57 := []*svcapitypes.ProcessorFeature{}
		for _, f57iter := range resp.DBInstance.ProcessorFeatures {
			f57elem := &svcapitypes.ProcessorFeature{}
			if f57iter.Name != nil {
				f57elem.Name = f57iter.Name
			}
			if f57iter.Value != nil {
				f57elem.Value = f57iter.Value
			}
			f57 = append(f57, f57elem)
		}
		ko.Spec.ProcessorFeatures = f57
	} else {
		ko.Spec.ProcessorFeatures = nil
	}
	if resp.DBInstance.PromotionTier != nil {
		ko.Spec.PromotionTier = resp.DBInstance.PromotionTier
	} else {
		ko.Spec.PromotionTier = nil
	}
	if resp.DBInstance.PubliclyAccessible != nil {
		ko.Spec.PubliclyAccessible = resp.DBInstance.PubliclyAccessible
	} else {
		ko.Spec.PubliclyAccessible = nil
	}
	if resp.DBInstance.ReadReplicaDBClusterIdentifiers != nil {
		f60 := []*string{}
		for _, f60iter := range resp.DBInstance.ReadReplicaDBClusterIdentifiers {
			var f60elem string
			f60elem = *f60iter
			f60 = append(f60, &f60elem)
		}
		ko.Status.ReadReplicaDBClusterIdentifiers = f60
	} else {
		ko.Status.ReadReplicaDBClusterIdentifiers = nil
	}
	if resp.DBInstance.ReadReplicaDBInstanceIdentifiers != nil {
		f61 := []*string{}
		for _, f61iter := range resp.DBInstance.ReadReplicaDBInstanceIdentifiers {
			var f61elem string
			f61elem = *f61iter
			f61 = append(f61, &f61elem)
		}
		ko.Status.ReadReplicaDBInstanceIdentifiers = f61
	} else {
		ko.Status.ReadReplicaDBInstanceIdentifiers = nil
	}
	if resp.DBInstance.ReadReplicaSourceDBInstanceIdentifier != nil {
		ko.Status.ReadReplicaSourceDBInstanceIdentifier = resp.DBInstance.ReadReplicaSourceDBInstanceIdentifier
	} else {
		ko.Status.ReadReplicaSourceDBInstanceIdentifier = nil
	}
	if resp.DBInstance.ReplicaMode != nil {
		ko.Status.ReplicaMode = resp.DBInstance.ReplicaMode
	} else {
		ko.Status.ReplicaMode = nil
	}
	if resp.DBInstance.ResumeFullAutomationModeTime != nil {
		ko.Status.ResumeFullAutomationModeTime = &metav1.Time{*resp.DBInstance.ResumeFullAutomationModeTime}
	} else {
		ko.Status.ResumeFullAutomationModeTime = nil
	}
	if resp.DBInstance.SecondaryAvailabilityZone != nil {
		ko.Status.SecondaryAvailabilityZone = resp.DBInstance.SecondaryAvailabilityZone
	} else {
		ko.Status.SecondaryAvailabilityZone = nil
	}
	if resp.DBInstance.StatusInfos != nil {
		f66 := []*svcapitypes.DBInstanceStatusInfo{}
		for _, f66iter := range resp.DBInstance.StatusInfos {
			f66elem := &svcapitypes.DBInstanceStatusInfo{}
			if f66iter.Message != nil {
				f66elem.Message = f66iter.Message
			}
			if f66iter.Normal != nil {
				f66elem.Normal = f66iter.Normal
			}
			if f66iter.Status != nil {
				f66elem.Status = f66iter.Status
			}
			if f66iter.StatusType != nil {
				f66elem.StatusType = f66iter.StatusType
			}
			f66 = append(f66, f66elem)
		}
		ko.Status.StatusInfos = f66
	} else {
		ko.Status.StatusInfos = nil
	}
	if resp.DBInstance.StorageEncrypted != nil {
		ko.Spec.StorageEncrypted = resp.DBInstance.StorageEncrypted
	} else {
		ko.Spec.StorageEncrypted = nil
	}
	if resp.DBInstance.StorageType != nil {
		ko.Spec.StorageType = resp.DBInstance.StorageType
	} else {
		ko.Spec.StorageType = nil
	}
	if resp.DBInstance.TagList != nil {
		f69 := []*svcapitypes.Tag{}
		for _, f69iter := range resp.DBInstance.TagList {
			f69elem := &svcapitypes.Tag{}
			if f69iter.Key != nil {
				f69elem.Key = f69iter.Key
			}
			if f69iter.Value != nil {
				f69elem.Value = f69iter.Value
			}
			f69 = append(f69, f69elem)
		}
		ko.Status.TagList = f69
	} else {
		ko.Status.TagList = nil
	}
	if resp.DBInstance.TdeCredentialArn != nil {
		ko.Spec.TDECredentialARN = resp.DBInstance.TdeCredentialArn
	} else {
		ko.Spec.TDECredentialARN = nil
	}
	if resp.DBInstance.Timezone != nil {
		ko.Spec.Timezone = resp.DBInstance.Timezone
	} else {
		ko.Spec.Timezone = nil
	}
	if resp.DBInstance.VpcSecurityGroups != nil {
		f72 := []*svcapitypes.VPCSecurityGroupMembership{}
		for _, f72iter := range resp.DBInstance.VpcSecurityGroups {
			f72elem := &svcapitypes.VPCSecurityGroupMembership{}
			if f72iter.Status != nil {
				f72elem.Status = f72iter.Status
			}
			if f72iter.VpcSecurityGroupId != nil {
				f72elem.VPCSecurityGroupID = f72iter.VpcSecurityGroupId
			}
			f72 = append(f72, f72elem)
		}
		ko.Status.VPCSecurityGroups = f72
	} else {
		ko.Status.VPCSecurityGroups = nil
	}

	rm.setStatusDefaults(ko)
	// We expect the DB instance to be in 'creating' status since we just
	// issued the call to create it, but I suppose it doesn't hurt to check
	// here.
	if instanceCreating(&resource{ko}) {
		// Setting resource synced condition to false will trigger a requeue of
		// the resource. No need to return a requeue error here.
		ackcondition.SetSynced(&resource{ko}, corev1.ConditionFalse, nil, nil)
		return &resource{ko}, nil
	}

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateDBInstanceInput, error) {
	res := &svcsdk.CreateDBInstanceInput{}

	if r.ko.Spec.AllocatedStorage != nil {
		res.SetAllocatedStorage(*r.ko.Spec.AllocatedStorage)
	}
	if r.ko.Spec.AutoMinorVersionUpgrade != nil {
		res.SetAutoMinorVersionUpgrade(*r.ko.Spec.AutoMinorVersionUpgrade)
	}
	if r.ko.Spec.AvailabilityZone != nil {
		res.SetAvailabilityZone(*r.ko.Spec.AvailabilityZone)
	}
	if r.ko.Spec.BackupRetentionPeriod != nil {
		res.SetBackupRetentionPeriod(*r.ko.Spec.BackupRetentionPeriod)
	}
	if r.ko.Spec.CharacterSetName != nil {
		res.SetCharacterSetName(*r.ko.Spec.CharacterSetName)
	}
	if r.ko.Spec.CopyTagsToSnapshot != nil {
		res.SetCopyTagsToSnapshot(*r.ko.Spec.CopyTagsToSnapshot)
	}
	if r.ko.Spec.CustomIAMInstanceProfile != nil {
		res.SetCustomIamInstanceProfile(*r.ko.Spec.CustomIAMInstanceProfile)
	}
	if r.ko.Spec.DBClusterIdentifier != nil {
		res.SetDBClusterIdentifier(*r.ko.Spec.DBClusterIdentifier)
	}
	if r.ko.Spec.DBInstanceClass != nil {
		res.SetDBInstanceClass(*r.ko.Spec.DBInstanceClass)
	}
	if r.ko.Spec.DBInstanceIdentifier != nil {
		res.SetDBInstanceIdentifier(*r.ko.Spec.DBInstanceIdentifier)
	}
	if r.ko.Spec.DBName != nil {
		res.SetDBName(*r.ko.Spec.DBName)
	}
	if r.ko.Spec.DBParameterGroupName != nil {
		res.SetDBParameterGroupName(*r.ko.Spec.DBParameterGroupName)
	}
	if r.ko.Spec.DBSecurityGroups != nil {
		f12 := []*string{}
		for _, f12iter := range r.ko.Spec.DBSecurityGroups {
			var f12elem string
			f12elem = *f12iter
			f12 = append(f12, &f12elem)
		}
		res.SetDBSecurityGroups(f12)
	}
	if r.ko.Spec.DBSubnetGroupName != nil {
		res.SetDBSubnetGroupName(*r.ko.Spec.DBSubnetGroupName)
	}
	if r.ko.Spec.DeletionProtection != nil {
		res.SetDeletionProtection(*r.ko.Spec.DeletionProtection)
	}
	if r.ko.Spec.Domain != nil {
		res.SetDomain(*r.ko.Spec.Domain)
	}
	if r.ko.Spec.DomainIAMRoleName != nil {
		res.SetDomainIAMRoleName(*r.ko.Spec.DomainIAMRoleName)
	}
	if r.ko.Spec.EnableCloudwatchLogsExports != nil {
		f17 := []*string{}
		for _, f17iter := range r.ko.Spec.EnableCloudwatchLogsExports {
			var f17elem string
			f17elem = *f17iter
			f17 = append(f17, &f17elem)
		}
		res.SetEnableCloudwatchLogsExports(f17)
	}
	if r.ko.Spec.EnableCustomerOwnedIP != nil {
		res.SetEnableCustomerOwnedIp(*r.ko.Spec.EnableCustomerOwnedIP)
	}
	if r.ko.Spec.EnableIAMDatabaseAuthentication != nil {
		res.SetEnableIAMDatabaseAuthentication(*r.ko.Spec.EnableIAMDatabaseAuthentication)
	}
	if r.ko.Spec.EnablePerformanceInsights != nil {
		res.SetEnablePerformanceInsights(*r.ko.Spec.EnablePerformanceInsights)
	}
	if r.ko.Spec.Engine != nil {
		res.SetEngine(*r.ko.Spec.Engine)
	}
	if r.ko.Spec.EngineVersion != nil {
		res.SetEngineVersion(*r.ko.Spec.EngineVersion)
	}
	if r.ko.Spec.IOPS != nil {
		res.SetIops(*r.ko.Spec.IOPS)
	}
	if r.ko.Spec.KMSKeyID != nil {
		res.SetKmsKeyId(*r.ko.Spec.KMSKeyID)
	}
	if r.ko.Spec.LicenseModel != nil {
		res.SetLicenseModel(*r.ko.Spec.LicenseModel)
	}
	if r.ko.Spec.MasterUserPassword != nil {
		tmpSecret, err := rm.rr.SecretValueFromReference(ctx, r.ko.Spec.MasterUserPassword)
		if err != nil {
			return nil, err
		}
		if tmpSecret != "" {
			res.SetMasterUserPassword(tmpSecret)
		}
	}
	if r.ko.Spec.MasterUsername != nil {
		res.SetMasterUsername(*r.ko.Spec.MasterUsername)
	}
	if r.ko.Spec.MaxAllocatedStorage != nil {
		res.SetMaxAllocatedStorage(*r.ko.Spec.MaxAllocatedStorage)
	}
	if r.ko.Spec.MonitoringInterval != nil {
		res.SetMonitoringInterval(*r.ko.Spec.MonitoringInterval)
	}
	if r.ko.Spec.MonitoringRoleARN != nil {
		res.SetMonitoringRoleArn(*r.ko.Spec.MonitoringRoleARN)
	}
	if r.ko.Spec.MultiAZ != nil {
		res.SetMultiAZ(*r.ko.Spec.MultiAZ)
	}
	if r.ko.Spec.NcharCharacterSetName != nil {
		res.SetNcharCharacterSetName(*r.ko.Spec.NcharCharacterSetName)
	}
	if r.ko.Spec.OptionGroupName != nil {
		res.SetOptionGroupName(*r.ko.Spec.OptionGroupName)
	}
	if r.ko.Spec.PerformanceInsightsKMSKeyID != nil {
		res.SetPerformanceInsightsKMSKeyId(*r.ko.Spec.PerformanceInsightsKMSKeyID)
	}
	if r.ko.Spec.PerformanceInsightsRetentionPeriod != nil {
		res.SetPerformanceInsightsRetentionPeriod(*r.ko.Spec.PerformanceInsightsRetentionPeriod)
	}
	if r.ko.Spec.Port != nil {
		res.SetPort(*r.ko.Spec.Port)
	}
	if r.ko.Spec.PreferredBackupWindow != nil {
		res.SetPreferredBackupWindow(*r.ko.Spec.PreferredBackupWindow)
	}
	if r.ko.Spec.PreferredMaintenanceWindow != nil {
		res.SetPreferredMaintenanceWindow(*r.ko.Spec.PreferredMaintenanceWindow)
	}
	if r.ko.Spec.ProcessorFeatures != nil {
		f39 := []*svcsdk.ProcessorFeature{}
		for _, f39iter := range r.ko.Spec.ProcessorFeatures {
			f39elem := &svcsdk.ProcessorFeature{}
			if f39iter.Name != nil {
				f39elem.SetName(*f39iter.Name)
			}
			if f39iter.Value != nil {
				f39elem.SetValue(*f39iter.Value)
			}
			f39 = append(f39, f39elem)
		}
		res.SetProcessorFeatures(f39)
	}
	if r.ko.Spec.PromotionTier != nil {
		res.SetPromotionTier(*r.ko.Spec.PromotionTier)
	}
	if r.ko.Spec.PubliclyAccessible != nil {
		res.SetPubliclyAccessible(*r.ko.Spec.PubliclyAccessible)
	}
	if r.ko.Spec.StorageEncrypted != nil {
		res.SetStorageEncrypted(*r.ko.Spec.StorageEncrypted)
	}
	if r.ko.Spec.StorageType != nil {
		res.SetStorageType(*r.ko.Spec.StorageType)
	}
	if r.ko.Spec.Tags != nil {
		f44 := []*svcsdk.Tag{}
		for _, f44iter := range r.ko.Spec.Tags {
			f44elem := &svcsdk.Tag{}
			if f44iter.Key != nil {
				f44elem.SetKey(*f44iter.Key)
			}
			if f44iter.Value != nil {
				f44elem.SetValue(*f44iter.Value)
			}
			f44 = append(f44, f44elem)
		}
		res.SetTags(f44)
	}
	if r.ko.Spec.TDECredentialARN != nil {
		res.SetTdeCredentialArn(*r.ko.Spec.TDECredentialARN)
	}
	if r.ko.Spec.TDECredentialPassword != nil {
		res.SetTdeCredentialPassword(*r.ko.Spec.TDECredentialPassword)
	}
	if r.ko.Spec.Timezone != nil {
		res.SetTimezone(*r.ko.Spec.Timezone)
	}
	if r.ko.Spec.VPCSecurityGroupIDs != nil {
		f48 := []*string{}
		for _, f48iter := range r.ko.Spec.VPCSecurityGroupIDs {
			var f48elem string
			f48elem = *f48iter
			f48 = append(f48, &f48elem)
		}
		res.SetVpcSecurityGroupIds(f48)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer exit(err)
	if instanceDeleting(latest) {
		msg := "DB instance is currently being deleted"
		ackcondition.SetSynced(desired, corev1.ConditionFalse, &msg, nil)
		return desired, requeueWaitWhileDeleting
	}
	if instanceCreating(latest) {
		msg := "DB instance is currently being created"
		ackcondition.SetSynced(desired, corev1.ConditionFalse, &msg, nil)
		return desired, requeueWaitUntilCanModify(latest)
	}
	if instanceHasTerminalStatus(latest) {
		msg := "DB instance is in '" + *latest.ko.Status.DBInstanceStatus + "' status"
		ackcondition.SetTerminal(desired, corev1.ConditionTrue, &msg, nil)
		ackcondition.SetSynced(desired, corev1.ConditionTrue, nil, nil)
		return desired, nil
	}
	if !instanceAvailable(latest) {
		msg := "DB instance cannot be modifed while in '" + *latest.ko.Status.DBInstanceStatus + "' status"
		ackcondition.SetSynced(desired, corev1.ConditionFalse, &msg, nil)
		return desired, requeueWaitUntilCanModify(latest)
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}
	// ModifyDBInstance call will return ValidationError when the
	// ModifyDBInstanceRequest contains the same DBSubnetGroupName
	// as the DBInstance. So, if there is no delta between
	// desired and latest for Spec.DBSubnetGroupName, exclude it
	// from ModifyDBInstanceRequest
	if !delta.DifferentAt("Spec.DBSubnetGroupName") {
		input.DBSubnetGroupName = nil
	}

	var resp *svcsdk.ModifyDBInstanceOutput
	_ = resp
	resp, err = rm.sdkapi.ModifyDBInstanceWithContext(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "ModifyDBInstance", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.DBInstance.ActivityStreamEngineNativeAuditFieldsIncluded != nil {
		ko.Status.ActivityStreamEngineNativeAuditFieldsIncluded = resp.DBInstance.ActivityStreamEngineNativeAuditFieldsIncluded
	} else {
		ko.Status.ActivityStreamEngineNativeAuditFieldsIncluded = nil
	}
	if resp.DBInstance.ActivityStreamKinesisStreamName != nil {
		ko.Status.ActivityStreamKinesisStreamName = resp.DBInstance.ActivityStreamKinesisStreamName
	} else {
		ko.Status.ActivityStreamKinesisStreamName = nil
	}
	if resp.DBInstance.ActivityStreamKmsKeyId != nil {
		ko.Status.ActivityStreamKMSKeyID = resp.DBInstance.ActivityStreamKmsKeyId
	} else {
		ko.Status.ActivityStreamKMSKeyID = nil
	}
	if resp.DBInstance.ActivityStreamMode != nil {
		ko.Status.ActivityStreamMode = resp.DBInstance.ActivityStreamMode
	} else {
		ko.Status.ActivityStreamMode = nil
	}
	if resp.DBInstance.ActivityStreamStatus != nil {
		ko.Status.ActivityStreamStatus = resp.DBInstance.ActivityStreamStatus
	} else {
		ko.Status.ActivityStreamStatus = nil
	}
	if resp.DBInstance.AllocatedStorage != nil {
		ko.Spec.AllocatedStorage = resp.DBInstance.AllocatedStorage
	} else {
		ko.Spec.AllocatedStorage = nil
	}
	if resp.DBInstance.AssociatedRoles != nil {
		f6 := []*svcapitypes.DBInstanceRole{}
		for _, f6iter := range resp.DBInstance.AssociatedRoles {
			f6elem := &svcapitypes.DBInstanceRole{}
			if f6iter.FeatureName != nil {
				f6elem.FeatureName = f6iter.FeatureName
			}
			if f6iter.RoleArn != nil {
				f6elem.RoleARN = f6iter.RoleArn
			}
			if f6iter.Status != nil {
				f6elem.Status = f6iter.Status
			}
			f6 = append(f6, f6elem)
		}
		ko.Status.AssociatedRoles = f6
	} else {
		ko.Status.AssociatedRoles = nil
	}
	if resp.DBInstance.AutoMinorVersionUpgrade != nil {
		ko.Spec.AutoMinorVersionUpgrade = resp.DBInstance.AutoMinorVersionUpgrade
	} else {
		ko.Spec.AutoMinorVersionUpgrade = nil
	}
	if resp.DBInstance.AutomaticRestartTime != nil {
		ko.Status.AutomaticRestartTime = &metav1.Time{*resp.DBInstance.AutomaticRestartTime}
	} else {
		ko.Status.AutomaticRestartTime = nil
	}
	if resp.DBInstance.AutomationMode != nil {
		ko.Status.AutomationMode = resp.DBInstance.AutomationMode
	} else {
		ko.Status.AutomationMode = nil
	}
	if resp.DBInstance.AvailabilityZone != nil {
		ko.Spec.AvailabilityZone = resp.DBInstance.AvailabilityZone
	} else {
		ko.Spec.AvailabilityZone = nil
	}
	if resp.DBInstance.AwsBackupRecoveryPointArn != nil {
		ko.Status.AWSBackupRecoveryPointARN = resp.DBInstance.AwsBackupRecoveryPointArn
	} else {
		ko.Status.AWSBackupRecoveryPointARN = nil
	}
	if resp.DBInstance.BackupRetentionPeriod != nil {
		ko.Spec.BackupRetentionPeriod = resp.DBInstance.BackupRetentionPeriod
	} else {
		ko.Spec.BackupRetentionPeriod = nil
	}
	if resp.DBInstance.CACertificateIdentifier != nil {
		ko.Status.CACertificateIdentifier = resp.DBInstance.CACertificateIdentifier
	} else {
		ko.Status.CACertificateIdentifier = nil
	}
	if resp.DBInstance.CharacterSetName != nil {
		ko.Spec.CharacterSetName = resp.DBInstance.CharacterSetName
	} else {
		ko.Spec.CharacterSetName = nil
	}
	if resp.DBInstance.CopyTagsToSnapshot != nil {
		ko.Spec.CopyTagsToSnapshot = resp.DBInstance.CopyTagsToSnapshot
	} else {
		ko.Spec.CopyTagsToSnapshot = nil
	}
	if resp.DBInstance.CustomIamInstanceProfile != nil {
		ko.Spec.CustomIAMInstanceProfile = resp.DBInstance.CustomIamInstanceProfile
	} else {
		ko.Spec.CustomIAMInstanceProfile = nil
	}
	if resp.DBInstance.CustomerOwnedIpEnabled != nil {
		ko.Status.CustomerOwnedIPEnabled = resp.DBInstance.CustomerOwnedIpEnabled
	} else {
		ko.Status.CustomerOwnedIPEnabled = nil
	}
	if resp.DBInstance.DBClusterIdentifier != nil {
		ko.Spec.DBClusterIdentifier = resp.DBInstance.DBClusterIdentifier
	} else {
		ko.Spec.DBClusterIdentifier = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.DBInstance.DBInstanceArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.DBInstance.DBInstanceArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.DBInstance.DBInstanceAutomatedBackupsReplications != nil {
		f20 := []*svcapitypes.DBInstanceAutomatedBackupsReplication{}
		for _, f20iter := range resp.DBInstance.DBInstanceAutomatedBackupsReplications {
			f20elem := &svcapitypes.DBInstanceAutomatedBackupsReplication{}
			if f20iter.DBInstanceAutomatedBackupsArn != nil {
				f20elem.DBInstanceAutomatedBackupsARN = f20iter.DBInstanceAutomatedBackupsArn
			}
			f20 = append(f20, f20elem)
		}
		ko.Status.DBInstanceAutomatedBackupsReplications = f20
	} else {
		ko.Status.DBInstanceAutomatedBackupsReplications = nil
	}
	if resp.DBInstance.DBInstanceClass != nil {
		ko.Spec.DBInstanceClass = resp.DBInstance.DBInstanceClass
	} else {
		ko.Spec.DBInstanceClass = nil
	}
	if resp.DBInstance.DBInstanceIdentifier != nil {
		ko.Spec.DBInstanceIdentifier = resp.DBInstance.DBInstanceIdentifier
	} else {
		ko.Spec.DBInstanceIdentifier = nil
	}
	if resp.DBInstance.DBInstanceStatus != nil {
		ko.Status.DBInstanceStatus = resp.DBInstance.DBInstanceStatus
	} else {
		ko.Status.DBInstanceStatus = nil
	}
	if resp.DBInstance.DBName != nil {
		ko.Spec.DBName = resp.DBInstance.DBName
	} else {
		ko.Spec.DBName = nil
	}
	if resp.DBInstance.DBParameterGroups != nil {
		f25 := []*svcapitypes.DBParameterGroupStatus_SDK{}
		for _, f25iter := range resp.DBInstance.DBParameterGroups {
			f25elem := &svcapitypes.DBParameterGroupStatus_SDK{}
			if f25iter.DBParameterGroupName != nil {
				f25elem.DBParameterGroupName = f25iter.DBParameterGroupName
			}
			if f25iter.ParameterApplyStatus != nil {
				f25elem.ParameterApplyStatus = f25iter.ParameterApplyStatus
			}
			f25 = append(f25, f25elem)
		}
		ko.Status.DBParameterGroups = f25
	} else {
		ko.Status.DBParameterGroups = nil
	}
	if resp.DBInstance.DBSecurityGroups != nil {
		f26 := []*string{}
		for _, f26iter := range resp.DBInstance.DBSecurityGroups {
			var f26elem string
			f26elem = *f26iter.DBSecurityGroupName
			f26 = append(f26, &f26elem)
		}
		ko.Spec.DBSecurityGroups = f26
	} else {
		ko.Spec.DBSecurityGroups = nil
	}
	if resp.DBInstance.DBSubnetGroup != nil {
		f27 := &svcapitypes.DBSubnetGroup_SDK{}
		if resp.DBInstance.DBSubnetGroup.DBSubnetGroupArn != nil {
			f27.DBSubnetGroupARN = resp.DBInstance.DBSubnetGroup.DBSubnetGroupArn
		}
		if resp.DBInstance.DBSubnetGroup.DBSubnetGroupDescription != nil {
			f27.DBSubnetGroupDescription = resp.DBInstance.DBSubnetGroup.DBSubnetGroupDescription
		}
		if resp.DBInstance.DBSubnetGroup.DBSubnetGroupName != nil {
			f27.DBSubnetGroupName = resp.DBInstance.DBSubnetGroup.DBSubnetGroupName
		}
		if resp.DBInstance.DBSubnetGroup.SubnetGroupStatus != nil {
			f27.SubnetGroupStatus = resp.DBInstance.DBSubnetGroup.SubnetGroupStatus
		}
		if resp.DBInstance.DBSubnetGroup.Subnets != nil {
			f27f4 := []*svcapitypes.Subnet{}
			for _, f27f4iter := range resp.DBInstance.DBSubnetGroup.Subnets {
				f27f4elem := &svcapitypes.Subnet{}
				if f27f4iter.SubnetAvailabilityZone != nil {
					f27f4elemf0 := &svcapitypes.AvailabilityZone{}
					if f27f4iter.SubnetAvailabilityZone.Name != nil {
						f27f4elemf0.Name = f27f4iter.SubnetAvailabilityZone.Name
					}
					f27f4elem.SubnetAvailabilityZone = f27f4elemf0
				}
				if f27f4iter.SubnetIdentifier != nil {
					f27f4elem.SubnetIdentifier = f27f4iter.SubnetIdentifier
				}
				if f27f4iter.SubnetOutpost != nil {
					f27f4elemf2 := &svcapitypes.Outpost{}
					if f27f4iter.SubnetOutpost.Arn != nil {
						f27f4elemf2.ARN = f27f4iter.SubnetOutpost.Arn
					}
					f27f4elem.SubnetOutpost = f27f4elemf2
				}
				if f27f4iter.SubnetStatus != nil {
					f27f4elem.SubnetStatus = f27f4iter.SubnetStatus
				}
				f27f4 = append(f27f4, f27f4elem)
			}
			f27.Subnets = f27f4
		}
		if resp.DBInstance.DBSubnetGroup.VpcId != nil {
			f27.VPCID = resp.DBInstance.DBSubnetGroup.VpcId
		}
		ko.Status.DBSubnetGroup = f27
	} else {
		ko.Status.DBSubnetGroup = nil
	}
	if resp.DBInstance.DbInstancePort != nil {
		ko.Status.DBInstancePort = resp.DBInstance.DbInstancePort
	} else {
		ko.Status.DBInstancePort = nil
	}
	if resp.DBInstance.DbiResourceId != nil {
		ko.Status.DBIResourceID = resp.DBInstance.DbiResourceId
	} else {
		ko.Status.DBIResourceID = nil
	}
	if resp.DBInstance.DeletionProtection != nil {
		ko.Spec.DeletionProtection = resp.DBInstance.DeletionProtection
	} else {
		ko.Spec.DeletionProtection = nil
	}
	if resp.DBInstance.DomainMemberships != nil {
		f31 := []*svcapitypes.DomainMembership{}
		for _, f31iter := range resp.DBInstance.DomainMemberships {
			f31elem := &svcapitypes.DomainMembership{}
			if f31iter.Domain != nil {
				f31elem.Domain = f31iter.Domain
			}
			if f31iter.FQDN != nil {
				f31elem.FQDN = f31iter.FQDN
			}
			if f31iter.IAMRoleName != nil {
				f31elem.IAMRoleName = f31iter.IAMRoleName
			}
			if f31iter.Status != nil {
				f31elem.Status = f31iter.Status
			}
			f31 = append(f31, f31elem)
		}
		ko.Status.DomainMemberships = f31
	} else {
		ko.Status.DomainMemberships = nil
	}
	if resp.DBInstance.EnabledCloudwatchLogsExports != nil {
		f32 := []*string{}
		for _, f32iter := range resp.DBInstance.EnabledCloudwatchLogsExports {
			var f32elem string
			f32elem = *f32iter
			f32 = append(f32, &f32elem)
		}
		ko.Status.EnabledCloudwatchLogsExports = f32
	} else {
		ko.Status.EnabledCloudwatchLogsExports = nil
	}
	if resp.DBInstance.Endpoint != nil {
		f33 := &svcapitypes.Endpoint{}
		if resp.DBInstance.Endpoint.Address != nil {
			f33.Address = resp.DBInstance.Endpoint.Address
		}
		if resp.DBInstance.Endpoint.HostedZoneId != nil {
			f33.HostedZoneID = resp.DBInstance.Endpoint.HostedZoneId
		}
		if resp.DBInstance.Endpoint.Port != nil {
			f33.Port = resp.DBInstance.Endpoint.Port
		}
		ko.Status.Endpoint = f33
	} else {
		ko.Status.Endpoint = nil
	}
	if resp.DBInstance.Engine != nil {
		ko.Spec.Engine = resp.DBInstance.Engine
	} else {
		ko.Spec.Engine = nil
	}
	if resp.DBInstance.EngineVersion != nil {
		ko.Spec.EngineVersion = resp.DBInstance.EngineVersion
	} else {
		ko.Spec.EngineVersion = nil
	}
	if resp.DBInstance.EnhancedMonitoringResourceArn != nil {
		ko.Status.EnhancedMonitoringResourceARN = resp.DBInstance.EnhancedMonitoringResourceArn
	} else {
		ko.Status.EnhancedMonitoringResourceARN = nil
	}
	if resp.DBInstance.IAMDatabaseAuthenticationEnabled != nil {
		ko.Status.IAMDatabaseAuthenticationEnabled = resp.DBInstance.IAMDatabaseAuthenticationEnabled
	} else {
		ko.Status.IAMDatabaseAuthenticationEnabled = nil
	}
	if resp.DBInstance.InstanceCreateTime != nil {
		ko.Status.InstanceCreateTime = &metav1.Time{*resp.DBInstance.InstanceCreateTime}
	} else {
		ko.Status.InstanceCreateTime = nil
	}
	if resp.DBInstance.Iops != nil {
		ko.Spec.IOPS = resp.DBInstance.Iops
	} else {
		ko.Spec.IOPS = nil
	}
	if resp.DBInstance.KmsKeyId != nil {
		ko.Spec.KMSKeyID = resp.DBInstance.KmsKeyId
	} else {
		ko.Spec.KMSKeyID = nil
	}
	if resp.DBInstance.LatestRestorableTime != nil {
		ko.Status.LatestRestorableTime = &metav1.Time{*resp.DBInstance.LatestRestorableTime}
	} else {
		ko.Status.LatestRestorableTime = nil
	}
	if resp.DBInstance.LicenseModel != nil {
		ko.Spec.LicenseModel = resp.DBInstance.LicenseModel
	} else {
		ko.Spec.LicenseModel = nil
	}
	if resp.DBInstance.ListenerEndpoint != nil {
		f43 := &svcapitypes.Endpoint{}
		if resp.DBInstance.ListenerEndpoint.Address != nil {
			f43.Address = resp.DBInstance.ListenerEndpoint.Address
		}
		if resp.DBInstance.ListenerEndpoint.HostedZoneId != nil {
			f43.HostedZoneID = resp.DBInstance.ListenerEndpoint.HostedZoneId
		}
		if resp.DBInstance.ListenerEndpoint.Port != nil {
			f43.Port = resp.DBInstance.ListenerEndpoint.Port
		}
		ko.Status.ListenerEndpoint = f43
	} else {
		ko.Status.ListenerEndpoint = nil
	}
	if resp.DBInstance.MasterUsername != nil {
		ko.Spec.MasterUsername = resp.DBInstance.MasterUsername
	} else {
		ko.Spec.MasterUsername = nil
	}
	if resp.DBInstance.MaxAllocatedStorage != nil {
		ko.Spec.MaxAllocatedStorage = resp.DBInstance.MaxAllocatedStorage
	} else {
		ko.Spec.MaxAllocatedStorage = nil
	}
	if resp.DBInstance.MonitoringInterval != nil {
		ko.Spec.MonitoringInterval = resp.DBInstance.MonitoringInterval
	} else {
		ko.Spec.MonitoringInterval = nil
	}
	if resp.DBInstance.MonitoringRoleArn != nil {
		ko.Spec.MonitoringRoleARN = resp.DBInstance.MonitoringRoleArn
	} else {
		ko.Spec.MonitoringRoleARN = nil
	}
	if resp.DBInstance.MultiAZ != nil {
		ko.Spec.MultiAZ = resp.DBInstance.MultiAZ
	} else {
		ko.Spec.MultiAZ = nil
	}
	if resp.DBInstance.NcharCharacterSetName != nil {
		ko.Spec.NcharCharacterSetName = resp.DBInstance.NcharCharacterSetName
	} else {
		ko.Spec.NcharCharacterSetName = nil
	}
	if resp.DBInstance.OptionGroupMemberships != nil {
		f50 := []*svcapitypes.OptionGroupMembership{}
		for _, f50iter := range resp.DBInstance.OptionGroupMemberships {
			f50elem := &svcapitypes.OptionGroupMembership{}
			if f50iter.OptionGroupName != nil {
				f50elem.OptionGroupName = f50iter.OptionGroupName
			}
			if f50iter.Status != nil {
				f50elem.Status = f50iter.Status
			}
			f50 = append(f50, f50elem)
		}
		ko.Status.OptionGroupMemberships = f50
	} else {
		ko.Status.OptionGroupMemberships = nil
	}
	if resp.DBInstance.PendingModifiedValues != nil {
		f51 := &svcapitypes.PendingModifiedValues{}
		if resp.DBInstance.PendingModifiedValues.AllocatedStorage != nil {
			f51.AllocatedStorage = resp.DBInstance.PendingModifiedValues.AllocatedStorage
		}
		if resp.DBInstance.PendingModifiedValues.AutomationMode != nil {
			f51.AutomationMode = resp.DBInstance.PendingModifiedValues.AutomationMode
		}
		if resp.DBInstance.PendingModifiedValues.BackupRetentionPeriod != nil {
			f51.BackupRetentionPeriod = resp.DBInstance.PendingModifiedValues.BackupRetentionPeriod
		}
		if resp.DBInstance.PendingModifiedValues.CACertificateIdentifier != nil {
			f51.CACertificateIdentifier = resp.DBInstance.PendingModifiedValues.CACertificateIdentifier
		}
		if resp.DBInstance.PendingModifiedValues.DBInstanceClass != nil {
			f51.DBInstanceClass = resp.DBInstance.PendingModifiedValues.DBInstanceClass
		}
		if resp.DBInstance.PendingModifiedValues.DBInstanceIdentifier != nil {
			f51.DBInstanceIdentifier = resp.DBInstance.PendingModifiedValues.DBInstanceIdentifier
		}
		if resp.DBInstance.PendingModifiedValues.DBSubnetGroupName != nil {
			f51.DBSubnetGroupName = resp.DBInstance.PendingModifiedValues.DBSubnetGroupName
		}
		if resp.DBInstance.PendingModifiedValues.EngineVersion != nil {
			f51.EngineVersion = resp.DBInstance.PendingModifiedValues.EngineVersion
		}
		if resp.DBInstance.PendingModifiedValues.IAMDatabaseAuthenticationEnabled != nil {
			f51.IAMDatabaseAuthenticationEnabled = resp.DBInstance.PendingModifiedValues.IAMDatabaseAuthenticationEnabled
		}
		if resp.DBInstance.PendingModifiedValues.Iops != nil {
			f51.IOPS = resp.DBInstance.PendingModifiedValues.Iops
		}
		if resp.DBInstance.PendingModifiedValues.LicenseModel != nil {
			f51.LicenseModel = resp.DBInstance.PendingModifiedValues.LicenseModel
		}
		if resp.DBInstance.PendingModifiedValues.MasterUserPassword != nil {
			f51.MasterUserPassword = resp.DBInstance.PendingModifiedValues.MasterUserPassword
		}
		if resp.DBInstance.PendingModifiedValues.MultiAZ != nil {
			f51.MultiAZ = resp.DBInstance.PendingModifiedValues.MultiAZ
		}
		if resp.DBInstance.PendingModifiedValues.PendingCloudwatchLogsExports != nil {
			f51f13 := &svcapitypes.PendingCloudwatchLogsExports{}
			if resp.DBInstance.PendingModifiedValues.PendingCloudwatchLogsExports.LogTypesToDisable != nil {
				f51f13f0 := []*string{}
				for _, f51f13f0iter := range resp.DBInstance.PendingModifiedValues.PendingCloudwatchLogsExports.LogTypesToDisable {
					var f51f13f0elem string
					f51f13f0elem = *f51f13f0iter
					f51f13f0 = append(f51f13f0, &f51f13f0elem)
				}
				f51f13.LogTypesToDisable = f51f13f0
			}
			if resp.DBInstance.PendingModifiedValues.PendingCloudwatchLogsExports.LogTypesToEnable != nil {
				f51f13f1 := []*string{}
				for _, f51f13f1iter := range resp.DBInstance.PendingModifiedValues.PendingCloudwatchLogsExports.LogTypesToEnable {
					var f51f13f1elem string
					f51f13f1elem = *f51f13f1iter
					f51f13f1 = append(f51f13f1, &f51f13f1elem)
				}
				f51f13.LogTypesToEnable = f51f13f1
			}
			f51.PendingCloudwatchLogsExports = f51f13
		}
		if resp.DBInstance.PendingModifiedValues.Port != nil {
			f51.Port = resp.DBInstance.PendingModifiedValues.Port
		}
		if resp.DBInstance.PendingModifiedValues.ProcessorFeatures != nil {
			f51f15 := []*svcapitypes.ProcessorFeature{}
			for _, f51f15iter := range resp.DBInstance.PendingModifiedValues.ProcessorFeatures {
				f51f15elem := &svcapitypes.ProcessorFeature{}
				if f51f15iter.Name != nil {
					f51f15elem.Name = f51f15iter.Name
				}
				if f51f15iter.Value != nil {
					f51f15elem.Value = f51f15iter.Value
				}
				f51f15 = append(f51f15, f51f15elem)
			}
			f51.ProcessorFeatures = f51f15
		}
		if resp.DBInstance.PendingModifiedValues.ResumeFullAutomationModeTime != nil {
			f51.ResumeFullAutomationModeTime = &metav1.Time{*resp.DBInstance.PendingModifiedValues.ResumeFullAutomationModeTime}
		}
		if resp.DBInstance.PendingModifiedValues.StorageType != nil {
			f51.StorageType = resp.DBInstance.PendingModifiedValues.StorageType
		}
		ko.Status.PendingModifiedValues = f51
	} else {
		ko.Status.PendingModifiedValues = nil
	}
	if resp.DBInstance.PerformanceInsightsEnabled != nil {
		ko.Status.PerformanceInsightsEnabled = resp.DBInstance.PerformanceInsightsEnabled
	} else {
		ko.Status.PerformanceInsightsEnabled = nil
	}
	if resp.DBInstance.PerformanceInsightsKMSKeyId != nil {
		ko.Spec.PerformanceInsightsKMSKeyID = resp.DBInstance.PerformanceInsightsKMSKeyId
	} else {
		ko.Spec.PerformanceInsightsKMSKeyID = nil
	}
	if resp.DBInstance.PerformanceInsightsRetentionPeriod != nil {
		ko.Spec.PerformanceInsightsRetentionPeriod = resp.DBInstance.PerformanceInsightsRetentionPeriod
	} else {
		ko.Spec.PerformanceInsightsRetentionPeriod = nil
	}
	if resp.DBInstance.PreferredBackupWindow != nil {
		ko.Spec.PreferredBackupWindow = resp.DBInstance.PreferredBackupWindow
	} else {
		ko.Spec.PreferredBackupWindow = nil
	}
	if resp.DBInstance.PreferredMaintenanceWindow != nil {
		ko.Spec.PreferredMaintenanceWindow = resp.DBInstance.PreferredMaintenanceWindow
	} else {
		ko.Spec.PreferredMaintenanceWindow = nil
	}
	if resp.DBInstance.ProcessorFeatures != nil {
		f57 := []*svcapitypes.ProcessorFeature{}
		for _, f57iter := range resp.DBInstance.ProcessorFeatures {
			f57elem := &svcapitypes.ProcessorFeature{}
			if f57iter.Name != nil {
				f57elem.Name = f57iter.Name
			}
			if f57iter.Value != nil {
				f57elem.Value = f57iter.Value
			}
			f57 = append(f57, f57elem)
		}
		ko.Spec.ProcessorFeatures = f57
	} else {
		ko.Spec.ProcessorFeatures = nil
	}
	if resp.DBInstance.PromotionTier != nil {
		ko.Spec.PromotionTier = resp.DBInstance.PromotionTier
	} else {
		ko.Spec.PromotionTier = nil
	}
	if resp.DBInstance.PubliclyAccessible != nil {
		ko.Spec.PubliclyAccessible = resp.DBInstance.PubliclyAccessible
	} else {
		ko.Spec.PubliclyAccessible = nil
	}
	if resp.DBInstance.ReadReplicaDBClusterIdentifiers != nil {
		f60 := []*string{}
		for _, f60iter := range resp.DBInstance.ReadReplicaDBClusterIdentifiers {
			var f60elem string
			f60elem = *f60iter
			f60 = append(f60, &f60elem)
		}
		ko.Status.ReadReplicaDBClusterIdentifiers = f60
	} else {
		ko.Status.ReadReplicaDBClusterIdentifiers = nil
	}
	if resp.DBInstance.ReadReplicaDBInstanceIdentifiers != nil {
		f61 := []*string{}
		for _, f61iter := range resp.DBInstance.ReadReplicaDBInstanceIdentifiers {
			var f61elem string
			f61elem = *f61iter
			f61 = append(f61, &f61elem)
		}
		ko.Status.ReadReplicaDBInstanceIdentifiers = f61
	} else {
		ko.Status.ReadReplicaDBInstanceIdentifiers = nil
	}
	if resp.DBInstance.ReadReplicaSourceDBInstanceIdentifier != nil {
		ko.Status.ReadReplicaSourceDBInstanceIdentifier = resp.DBInstance.ReadReplicaSourceDBInstanceIdentifier
	} else {
		ko.Status.ReadReplicaSourceDBInstanceIdentifier = nil
	}
	if resp.DBInstance.ReplicaMode != nil {
		ko.Status.ReplicaMode = resp.DBInstance.ReplicaMode
	} else {
		ko.Status.ReplicaMode = nil
	}
	if resp.DBInstance.ResumeFullAutomationModeTime != nil {
		ko.Status.ResumeFullAutomationModeTime = &metav1.Time{*resp.DBInstance.ResumeFullAutomationModeTime}
	} else {
		ko.Status.ResumeFullAutomationModeTime = nil
	}
	if resp.DBInstance.SecondaryAvailabilityZone != nil {
		ko.Status.SecondaryAvailabilityZone = resp.DBInstance.SecondaryAvailabilityZone
	} else {
		ko.Status.SecondaryAvailabilityZone = nil
	}
	if resp.DBInstance.StatusInfos != nil {
		f66 := []*svcapitypes.DBInstanceStatusInfo{}
		for _, f66iter := range resp.DBInstance.StatusInfos {
			f66elem := &svcapitypes.DBInstanceStatusInfo{}
			if f66iter.Message != nil {
				f66elem.Message = f66iter.Message
			}
			if f66iter.Normal != nil {
				f66elem.Normal = f66iter.Normal
			}
			if f66iter.Status != nil {
				f66elem.Status = f66iter.Status
			}
			if f66iter.StatusType != nil {
				f66elem.StatusType = f66iter.StatusType
			}
			f66 = append(f66, f66elem)
		}
		ko.Status.StatusInfos = f66
	} else {
		ko.Status.StatusInfos = nil
	}
	if resp.DBInstance.StorageEncrypted != nil {
		ko.Spec.StorageEncrypted = resp.DBInstance.StorageEncrypted
	} else {
		ko.Spec.StorageEncrypted = nil
	}
	if resp.DBInstance.StorageType != nil {
		ko.Spec.StorageType = resp.DBInstance.StorageType
	} else {
		ko.Spec.StorageType = nil
	}
	if resp.DBInstance.TagList != nil {
		f69 := []*svcapitypes.Tag{}
		for _, f69iter := range resp.DBInstance.TagList {
			f69elem := &svcapitypes.Tag{}
			if f69iter.Key != nil {
				f69elem.Key = f69iter.Key
			}
			if f69iter.Value != nil {
				f69elem.Value = f69iter.Value
			}
			f69 = append(f69, f69elem)
		}
		ko.Status.TagList = f69
	} else {
		ko.Status.TagList = nil
	}
	if resp.DBInstance.TdeCredentialArn != nil {
		ko.Spec.TDECredentialARN = resp.DBInstance.TdeCredentialArn
	} else {
		ko.Spec.TDECredentialARN = nil
	}
	if resp.DBInstance.Timezone != nil {
		ko.Spec.Timezone = resp.DBInstance.Timezone
	} else {
		ko.Spec.Timezone = nil
	}
	if resp.DBInstance.VpcSecurityGroups != nil {
		f72 := []*svcapitypes.VPCSecurityGroupMembership{}
		for _, f72iter := range resp.DBInstance.VpcSecurityGroups {
			f72elem := &svcapitypes.VPCSecurityGroupMembership{}
			if f72iter.Status != nil {
				f72elem.Status = f72iter.Status
			}
			if f72iter.VpcSecurityGroupId != nil {
				f72elem.VPCSecurityGroupID = f72iter.VpcSecurityGroupId
			}
			f72 = append(f72, f72elem)
		}
		ko.Status.VPCSecurityGroups = f72
	} else {
		ko.Status.VPCSecurityGroups = nil
	}

	rm.setStatusDefaults(ko)
	// If there was no error during update, requeue the request.
	// When ModifyDBInstance API is successful, it asynchronously
	// updates the DBInstanceStatus. Requeue to find the current
	// DBInstance status and set Synced condition accordingly
	if err == nil {
		return &resource{ko}, customWaitAtferUpdate
	}

	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.ModifyDBInstanceInput, error) {
	res := &svcsdk.ModifyDBInstanceInput{}

	if r.ko.Spec.AllocatedStorage != nil {
		res.SetAllocatedStorage(*r.ko.Spec.AllocatedStorage)
	}
	res.SetApplyImmediately(true)
	if r.ko.Spec.AutoMinorVersionUpgrade != nil {
		res.SetAutoMinorVersionUpgrade(*r.ko.Spec.AutoMinorVersionUpgrade)
	}
	if r.ko.Status.AutomationMode != nil {
		res.SetAutomationMode(*r.ko.Status.AutomationMode)
	}
	if r.ko.Status.AWSBackupRecoveryPointARN != nil {
		res.SetAwsBackupRecoveryPointArn(*r.ko.Status.AWSBackupRecoveryPointARN)
	}
	if r.ko.Spec.BackupRetentionPeriod != nil {
		res.SetBackupRetentionPeriod(*r.ko.Spec.BackupRetentionPeriod)
	}
	if r.ko.Status.CACertificateIdentifier != nil {
		res.SetCACertificateIdentifier(*r.ko.Status.CACertificateIdentifier)
	}
	if r.ko.Spec.CopyTagsToSnapshot != nil {
		res.SetCopyTagsToSnapshot(*r.ko.Spec.CopyTagsToSnapshot)
	}
	if r.ko.Spec.DBInstanceClass != nil {
		res.SetDBInstanceClass(*r.ko.Spec.DBInstanceClass)
	}
	if r.ko.Spec.DBInstanceIdentifier != nil {
		res.SetDBInstanceIdentifier(*r.ko.Spec.DBInstanceIdentifier)
	}
	if r.ko.Spec.DBParameterGroupName != nil {
		res.SetDBParameterGroupName(*r.ko.Spec.DBParameterGroupName)
	}
	if r.ko.Spec.DBSecurityGroups != nil {
		f15 := []*string{}
		for _, f15iter := range r.ko.Spec.DBSecurityGroups {
			var f15elem string
			f15elem = *f15iter
			f15 = append(f15, &f15elem)
		}
		res.SetDBSecurityGroups(f15)
	}
	if r.ko.Spec.DBSubnetGroupName != nil {
		res.SetDBSubnetGroupName(*r.ko.Spec.DBSubnetGroupName)
	}
	if r.ko.Spec.DeletionProtection != nil {
		res.SetDeletionProtection(*r.ko.Spec.DeletionProtection)
	}
	if r.ko.Spec.Domain != nil {
		res.SetDomain(*r.ko.Spec.Domain)
	}
	if r.ko.Spec.DomainIAMRoleName != nil {
		res.SetDomainIAMRoleName(*r.ko.Spec.DomainIAMRoleName)
	}
	if r.ko.Spec.EnableCustomerOwnedIP != nil {
		res.SetEnableCustomerOwnedIp(*r.ko.Spec.EnableCustomerOwnedIP)
	}
	if r.ko.Spec.EnableIAMDatabaseAuthentication != nil {
		res.SetEnableIAMDatabaseAuthentication(*r.ko.Spec.EnableIAMDatabaseAuthentication)
	}
	if r.ko.Spec.EnablePerformanceInsights != nil {
		res.SetEnablePerformanceInsights(*r.ko.Spec.EnablePerformanceInsights)
	}
	if r.ko.Spec.EngineVersion != nil {
		res.SetEngineVersion(*r.ko.Spec.EngineVersion)
	}
	if r.ko.Spec.IOPS != nil {
		res.SetIops(*r.ko.Spec.IOPS)
	}
	if r.ko.Spec.LicenseModel != nil {
		res.SetLicenseModel(*r.ko.Spec.LicenseModel)
	}
	if r.ko.Spec.MasterUserPassword != nil {
		tmpSecret, err := rm.rr.SecretValueFromReference(ctx, r.ko.Spec.MasterUserPassword)
		if err != nil {
			return nil, err
		}
		if tmpSecret != "" {
			res.SetMasterUserPassword(tmpSecret)
		}
	}
	if r.ko.Spec.MaxAllocatedStorage != nil {
		res.SetMaxAllocatedStorage(*r.ko.Spec.MaxAllocatedStorage)
	}
	if r.ko.Spec.MonitoringInterval != nil {
		res.SetMonitoringInterval(*r.ko.Spec.MonitoringInterval)
	}
	if r.ko.Spec.MonitoringRoleARN != nil {
		res.SetMonitoringRoleArn(*r.ko.Spec.MonitoringRoleARN)
	}
	if r.ko.Spec.MultiAZ != nil {
		res.SetMultiAZ(*r.ko.Spec.MultiAZ)
	}
	if r.ko.Spec.OptionGroupName != nil {
		res.SetOptionGroupName(*r.ko.Spec.OptionGroupName)
	}
	if r.ko.Spec.PerformanceInsightsKMSKeyID != nil {
		res.SetPerformanceInsightsKMSKeyId(*r.ko.Spec.PerformanceInsightsKMSKeyID)
	}
	if r.ko.Spec.PerformanceInsightsRetentionPeriod != nil {
		res.SetPerformanceInsightsRetentionPeriod(*r.ko.Spec.PerformanceInsightsRetentionPeriod)
	}
	if r.ko.Spec.PreferredBackupWindow != nil {
		res.SetPreferredBackupWindow(*r.ko.Spec.PreferredBackupWindow)
	}
	if r.ko.Spec.PreferredMaintenanceWindow != nil {
		res.SetPreferredMaintenanceWindow(*r.ko.Spec.PreferredMaintenanceWindow)
	}
	if r.ko.Spec.ProcessorFeatures != nil {
		f37 := []*svcsdk.ProcessorFeature{}
		for _, f37iter := range r.ko.Spec.ProcessorFeatures {
			f37elem := &svcsdk.ProcessorFeature{}
			if f37iter.Name != nil {
				f37elem.SetName(*f37iter.Name)
			}
			if f37iter.Value != nil {
				f37elem.SetValue(*f37iter.Value)
			}
			f37 = append(f37, f37elem)
		}
		res.SetProcessorFeatures(f37)
	}
	if r.ko.Spec.PromotionTier != nil {
		res.SetPromotionTier(*r.ko.Spec.PromotionTier)
	}
	if r.ko.Spec.PubliclyAccessible != nil {
		res.SetPubliclyAccessible(*r.ko.Spec.PubliclyAccessible)
	}
	if r.ko.Status.ReplicaMode != nil {
		res.SetReplicaMode(*r.ko.Status.ReplicaMode)
	}
	if r.ko.Spec.StorageType != nil {
		res.SetStorageType(*r.ko.Spec.StorageType)
	}
	if r.ko.Spec.TDECredentialARN != nil {
		res.SetTdeCredentialArn(*r.ko.Spec.TDECredentialARN)
	}
	if r.ko.Spec.TDECredentialPassword != nil {
		res.SetTdeCredentialPassword(*r.ko.Spec.TDECredentialPassword)
	}
	if r.ko.Spec.VPCSecurityGroupIDs != nil {
		f46 := []*string{}
		for _, f46iter := range r.ko.Spec.VPCSecurityGroupIDs {
			var f46elem string
			f46elem = *f46iter
			f46 = append(f46, &f46elem)
		}
		res.SetVpcSecurityGroupIds(f46)
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer exit(err)
	if instanceDeleting(r) {
		return r, requeueWaitWhileDeleting
	}

	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteDBInstanceOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteDBInstanceWithContext(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteDBInstance", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteDBInstanceInput, error) {
	res := &svcsdk.DeleteDBInstanceInput{}

	if r.ko.Spec.DBInstanceIdentifier != nil {
		res.SetDBInstanceIdentifier(*r.ko.Spec.DBInstanceIdentifier)
	}
	res.SetSkipFinalSnapshot(true)

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.DBInstance,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}

	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}
	awsErr, ok := ackerr.AWSError(err)
	if !ok {
		return false
	}
	switch awsErr.Code() {
	case "InvalidParameter",
		"InvalidParameterValue",
		"InvalidParameterCombination",
		"DBSecurityGroupNotFound",
		"DBSubnetGroupNotFoundFault",
		"DBParameterGroupNotFound":
		return true
	default:
		return false
	}
}
