apiVersion: rbac.authorization.k8s.io/v1
{{ if eq .Values.installScope "cluster" }}
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ack-rds-controller
{{ else }}
kind: Role
metadata:
  creationTimestamp: null
  name: ack-rds-controller
  namespace: {{ .Release.Namespace }}
{{ end }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - kms.services.k8s.aws
  resources:
  - keys
  verbs:
  - get
  - list
- apiGroups:
  - kms.services.k8s.aws
  resources:
  - keys/status
  verbs:
  - get
  - list
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbclusterparametergroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbclusterparametergroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbparametergroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbparametergroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbsubnetgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbsubnetgroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - globalclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - globalclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - services.k8s.aws
  resources:
  - adoptedresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.k8s.aws
  resources:
  - adoptedresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - services.k8s.aws
  resources:
  - fieldexports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.k8s.aws
  resources:
  - fieldexports/status
  verbs:
  - get
  - patch
  - update
