---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-rds-writer
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbinstances

  - dbparametergroups

  - dbsecuritygroups

  - dbsubnetgroups

  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbinstances
  - dbparametergroups
  - dbsecuritygroups
  - dbsubnetgroups
  verbs:
  - get
  - patch
  - update
