---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ include "ack-rds-controller.app.fullname" . }}-reader
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ack-rds-controller.app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    k8s-app: {{ include "ack-rds-controller.app.name" . }}
    helm.sh/chart: {{ include "ack-rds-controller.chart.name-version" . }}
rules:
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbclusters
  - dbclusterendpoints
  - dbclusterparametergroups
  - dbclustersnapshots
  - dbinstances
  - dbparametergroups
  - dbproxies
  - dbsnapshots
  - dbsubnetgroups
  - globalclusters
  verbs:
  - get
  - list
  - watch
