// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package option_group

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}
	compareTags(delta, a, b)

	if ackcompare.HasNilDifference(a.ko.Spec.EngineName, b.ko.Spec.EngineName) {
		delta.Add("Spec.EngineName", a.ko.Spec.EngineName, b.ko.Spec.EngineName)
	} else if a.ko.Spec.EngineName != nil && b.ko.Spec.EngineName != nil {
		if *a.ko.Spec.EngineName != *b.ko.Spec.EngineName {
			delta.Add("Spec.EngineName", a.ko.Spec.EngineName, b.ko.Spec.EngineName)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MajorEngineVersion, b.ko.Spec.MajorEngineVersion) {
		delta.Add("Spec.MajorEngineVersion", a.ko.Spec.MajorEngineVersion, b.ko.Spec.MajorEngineVersion)
	} else if a.ko.Spec.MajorEngineVersion != nil && b.ko.Spec.MajorEngineVersion != nil {
		if *a.ko.Spec.MajorEngineVersion != *b.ko.Spec.MajorEngineVersion {
			delta.Add("Spec.MajorEngineVersion", a.ko.Spec.MajorEngineVersion, b.ko.Spec.MajorEngineVersion)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.OptionGroupDescription, b.ko.Spec.OptionGroupDescription) {
		delta.Add("Spec.OptionGroupDescription", a.ko.Spec.OptionGroupDescription, b.ko.Spec.OptionGroupDescription)
	} else if a.ko.Spec.OptionGroupDescription != nil && b.ko.Spec.OptionGroupDescription != nil {
		if *a.ko.Spec.OptionGroupDescription != *b.ko.Spec.OptionGroupDescription {
			delta.Add("Spec.OptionGroupDescription", a.ko.Spec.OptionGroupDescription, b.ko.Spec.OptionGroupDescription)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.OptionGroupName, b.ko.Spec.OptionGroupName) {
		delta.Add("Spec.OptionGroupName", a.ko.Spec.OptionGroupName, b.ko.Spec.OptionGroupName)
	} else if a.ko.Spec.OptionGroupName != nil && b.ko.Spec.OptionGroupName != nil {
		if *a.ko.Spec.OptionGroupName != *b.ko.Spec.OptionGroupName {
			delta.Add("Spec.OptionGroupName", a.ko.Spec.OptionGroupName, b.ko.Spec.OptionGroupName)
		}
	}

	return delta
}
