// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package option_group

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/rds"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/rds/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/rds-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.OptionGroup{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadManyInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DescribeOptionGroupsOutput
	resp, err = rm.sdkapi.DescribeOptionGroups(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "DescribeOptionGroups", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "OptionGroupNotFoundFault" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.OptionGroupsList {
		if elem.AllowsVpcAndNonVpcInstanceMemberships != nil {
			ko.Status.AllowsVPCAndNonVPCInstanceMemberships = elem.AllowsVpcAndNonVpcInstanceMemberships
		} else {
			ko.Status.AllowsVPCAndNonVPCInstanceMemberships = nil
		}
		if elem.CopyTimestamp != nil {
			ko.Status.CopyTimestamp = &metav1.Time{*elem.CopyTimestamp}
		} else {
			ko.Status.CopyTimestamp = nil
		}
		if elem.EngineName != nil {
			ko.Spec.EngineName = elem.EngineName
		} else {
			ko.Spec.EngineName = nil
		}
		if elem.MajorEngineVersion != nil {
			ko.Spec.MajorEngineVersion = elem.MajorEngineVersion
		} else {
			ko.Spec.MajorEngineVersion = nil
		}
		if elem.OptionGroupArn != nil {
			if ko.Status.ACKResourceMetadata == nil {
				ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
			}
			tmpARN := ackv1alpha1.AWSResourceName(*elem.OptionGroupArn)
			ko.Status.ACKResourceMetadata.ARN = &tmpARN
		}
		if elem.OptionGroupDescription != nil {
			ko.Spec.Description = elem.OptionGroupDescription
		} else {
			ko.Spec.Description = nil
		}
		if elem.OptionGroupName != nil {
			ko.Spec.Name = elem.OptionGroupName
		} else {
			ko.Spec.Name = nil
		}
		if elem.Options != nil {
			f7 := []*svcapitypes.Option{}
			for _, f7iter := range elem.Options {
				f7elem := &svcapitypes.Option{}
				if f7iter.DBSecurityGroupMemberships != nil {
					f7elemf0 := []*svcapitypes.DBSecurityGroupMembership{}
					for _, f7elemf0iter := range f7iter.DBSecurityGroupMemberships {
						f7elemf0elem := &svcapitypes.DBSecurityGroupMembership{}
						if f7elemf0iter.DBSecurityGroupName != nil {
							f7elemf0elem.DBSecurityGroupName = f7elemf0iter.DBSecurityGroupName
						}
						if f7elemf0iter.Status != nil {
							f7elemf0elem.Status = f7elemf0iter.Status
						}
						f7elemf0 = append(f7elemf0, f7elemf0elem)
					}
					f7elem.DBSecurityGroupMemberships = f7elemf0
				}
				if f7iter.OptionDescription != nil {
					f7elem.OptionDescription = f7iter.OptionDescription
				}
				if f7iter.OptionName != nil {
					f7elem.OptionName = f7iter.OptionName
				}
				if f7iter.OptionSettings != nil {
					f7elemf3 := []*svcapitypes.OptionSetting{}
					for _, f7elemf3iter := range f7iter.OptionSettings {
						f7elemf3elem := &svcapitypes.OptionSetting{}
						if f7elemf3iter.AllowedValues != nil {
							f7elemf3elem.AllowedValues = f7elemf3iter.AllowedValues
						}
						if f7elemf3iter.ApplyType != nil {
							f7elemf3elem.ApplyType = f7elemf3iter.ApplyType
						}
						if f7elemf3iter.DataType != nil {
							f7elemf3elem.DataType = f7elemf3iter.DataType
						}
						if f7elemf3iter.DefaultValue != nil {
							f7elemf3elem.DefaultValue = f7elemf3iter.DefaultValue
						}
						if f7elemf3iter.Description != nil {
							f7elemf3elem.Description = f7elemf3iter.Description
						}
						if f7elemf3iter.IsCollection != nil {
							f7elemf3elem.IsCollection = f7elemf3iter.IsCollection
						}
						if f7elemf3iter.IsModifiable != nil {
							f7elemf3elem.IsModifiable = f7elemf3iter.IsModifiable
						}
						if f7elemf3iter.Name != nil {
							f7elemf3elem.Name = f7elemf3iter.Name
						}
						if f7elemf3iter.Value != nil {
							f7elemf3elem.Value = f7elemf3iter.Value
						}
						f7elemf3 = append(f7elemf3, f7elemf3elem)
					}
					f7elem.OptionSettings = f7elemf3
				}
				if f7iter.OptionVersion != nil {
					f7elem.OptionVersion = f7iter.OptionVersion
				}
				if f7iter.Permanent != nil {
					f7elem.Permanent = f7iter.Permanent
				}
				if f7iter.Persistent != nil {
					f7elem.Persistent = f7iter.Persistent
				}
				if f7iter.Port != nil {
					portCopy := int64(*f7iter.Port)
					f7elem.Port = &portCopy
				}
				if f7iter.VpcSecurityGroupMemberships != nil {
					f7elemf8 := []*svcapitypes.VPCSecurityGroupMembership{}
					for _, f7elemf8iter := range f7iter.VpcSecurityGroupMemberships {
						f7elemf8elem := &svcapitypes.VPCSecurityGroupMembership{}
						if f7elemf8iter.Status != nil {
							f7elemf8elem.Status = f7elemf8iter.Status
						}
						if f7elemf8iter.VpcSecurityGroupId != nil {
							f7elemf8elem.VPCSecurityGroupID = f7elemf8iter.VpcSecurityGroupId
						}
						f7elemf8 = append(f7elemf8, f7elemf8elem)
					}
					f7elem.VPCSecurityGroupMemberships = f7elemf8
				}
				f7 = append(f7, f7elem)
			}
			ko.Status.Options = f7
		} else {
			ko.Status.Options = nil
		}
		if elem.SourceAccountId != nil {
			ko.Status.SourceAccountID = elem.SourceAccountId
		} else {
			ko.Status.SourceAccountID = nil
		}
		if elem.SourceOptionGroup != nil {
			ko.Status.SourceOptionGroup = elem.SourceOptionGroup
		} else {
			ko.Status.SourceOptionGroup = nil
		}
		if elem.VpcId != nil {
			ko.Status.VPCID = elem.VpcId
		} else {
			ko.Status.VPCID = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)
	if ko.Status.ACKResourceMetadata != nil && ko.Status.ACKResourceMetadata.ARN != nil {
		resourceARN := (*string)(ko.Status.ACKResourceMetadata.ARN)
		tags, err := rm.getTags(ctx, *resourceARN)
		if err != nil {
			return nil, err
		}
		ko.Spec.Tags = tags
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadManyInput returns true if there are any fields
// for the ReadMany Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadManyInput(
	r *resource,
) bool {
	return r.ko.Spec.Name == nil

}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeOptionGroupsInput, error) {
	res := &svcsdk.DescribeOptionGroupsInput{}

	if r.ko.Spec.EngineName != nil {
		res.EngineName = r.ko.Spec.EngineName
	}
	if r.ko.Spec.MajorEngineVersion != nil {
		res.MajorEngineVersion = r.ko.Spec.MajorEngineVersion
	}
	if r.ko.Spec.Name != nil {
		res.OptionGroupName = r.ko.Spec.Name
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateOptionGroupOutput
	_ = resp
	resp, err = rm.sdkapi.CreateOptionGroup(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateOptionGroup", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.OptionGroup.AllowsVpcAndNonVpcInstanceMemberships != nil {
		ko.Status.AllowsVPCAndNonVPCInstanceMemberships = resp.OptionGroup.AllowsVpcAndNonVpcInstanceMemberships
	} else {
		ko.Status.AllowsVPCAndNonVPCInstanceMemberships = nil
	}
	if resp.OptionGroup.CopyTimestamp != nil {
		ko.Status.CopyTimestamp = &metav1.Time{*resp.OptionGroup.CopyTimestamp}
	} else {
		ko.Status.CopyTimestamp = nil
	}
	if resp.OptionGroup.EngineName != nil {
		ko.Spec.EngineName = resp.OptionGroup.EngineName
	} else {
		ko.Spec.EngineName = nil
	}
	if resp.OptionGroup.MajorEngineVersion != nil {
		ko.Spec.MajorEngineVersion = resp.OptionGroup.MajorEngineVersion
	} else {
		ko.Spec.MajorEngineVersion = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.OptionGroup.OptionGroupArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.OptionGroup.OptionGroupArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.OptionGroup.OptionGroupDescription != nil {
		ko.Spec.Description = resp.OptionGroup.OptionGroupDescription
	} else {
		ko.Spec.Description = nil
	}
	if resp.OptionGroup.OptionGroupName != nil {
		ko.Spec.Name = resp.OptionGroup.OptionGroupName
	} else {
		ko.Spec.Name = nil
	}
	if resp.OptionGroup.Options != nil {
		f7 := []*svcapitypes.Option{}
		for _, f7iter := range resp.OptionGroup.Options {
			f7elem := &svcapitypes.Option{}
			if f7iter.DBSecurityGroupMemberships != nil {
				f7elemf0 := []*svcapitypes.DBSecurityGroupMembership{}
				for _, f7elemf0iter := range f7iter.DBSecurityGroupMemberships {
					f7elemf0elem := &svcapitypes.DBSecurityGroupMembership{}
					if f7elemf0iter.DBSecurityGroupName != nil {
						f7elemf0elem.DBSecurityGroupName = f7elemf0iter.DBSecurityGroupName
					}
					if f7elemf0iter.Status != nil {
						f7elemf0elem.Status = f7elemf0iter.Status
					}
					f7elemf0 = append(f7elemf0, f7elemf0elem)
				}
				f7elem.DBSecurityGroupMemberships = f7elemf0
			}
			if f7iter.OptionDescription != nil {
				f7elem.OptionDescription = f7iter.OptionDescription
			}
			if f7iter.OptionName != nil {
				f7elem.OptionName = f7iter.OptionName
			}
			if f7iter.OptionSettings != nil {
				f7elemf3 := []*svcapitypes.OptionSetting{}
				for _, f7elemf3iter := range f7iter.OptionSettings {
					f7elemf3elem := &svcapitypes.OptionSetting{}
					if f7elemf3iter.AllowedValues != nil {
						f7elemf3elem.AllowedValues = f7elemf3iter.AllowedValues
					}
					if f7elemf3iter.ApplyType != nil {
						f7elemf3elem.ApplyType = f7elemf3iter.ApplyType
					}
					if f7elemf3iter.DataType != nil {
						f7elemf3elem.DataType = f7elemf3iter.DataType
					}
					if f7elemf3iter.DefaultValue != nil {
						f7elemf3elem.DefaultValue = f7elemf3iter.DefaultValue
					}
					if f7elemf3iter.Description != nil {
						f7elemf3elem.Description = f7elemf3iter.Description
					}
					if f7elemf3iter.IsCollection != nil {
						f7elemf3elem.IsCollection = f7elemf3iter.IsCollection
					}
					if f7elemf3iter.IsModifiable != nil {
						f7elemf3elem.IsModifiable = f7elemf3iter.IsModifiable
					}
					if f7elemf3iter.Name != nil {
						f7elemf3elem.Name = f7elemf3iter.Name
					}
					if f7elemf3iter.Value != nil {
						f7elemf3elem.Value = f7elemf3iter.Value
					}
					f7elemf3 = append(f7elemf3, f7elemf3elem)
				}
				f7elem.OptionSettings = f7elemf3
			}
			if f7iter.OptionVersion != nil {
				f7elem.OptionVersion = f7iter.OptionVersion
			}
			if f7iter.Permanent != nil {
				f7elem.Permanent = f7iter.Permanent
			}
			if f7iter.Persistent != nil {
				f7elem.Persistent = f7iter.Persistent
			}
			if f7iter.Port != nil {
				portCopy := int64(*f7iter.Port)
				f7elem.Port = &portCopy
			}
			if f7iter.VpcSecurityGroupMemberships != nil {
				f7elemf8 := []*svcapitypes.VPCSecurityGroupMembership{}
				for _, f7elemf8iter := range f7iter.VpcSecurityGroupMemberships {
					f7elemf8elem := &svcapitypes.VPCSecurityGroupMembership{}
					if f7elemf8iter.Status != nil {
						f7elemf8elem.Status = f7elemf8iter.Status
					}
					if f7elemf8iter.VpcSecurityGroupId != nil {
						f7elemf8elem.VPCSecurityGroupID = f7elemf8iter.VpcSecurityGroupId
					}
					f7elemf8 = append(f7elemf8, f7elemf8elem)
				}
				f7elem.VPCSecurityGroupMemberships = f7elemf8
			}
			f7 = append(f7, f7elem)
		}
		ko.Status.Options = f7
	} else {
		ko.Status.Options = nil
	}
	if resp.OptionGroup.SourceAccountId != nil {
		ko.Status.SourceAccountID = resp.OptionGroup.SourceAccountId
	} else {
		ko.Status.SourceAccountID = nil
	}
	if resp.OptionGroup.SourceOptionGroup != nil {
		ko.Status.SourceOptionGroup = resp.OptionGroup.SourceOptionGroup
	} else {
		ko.Status.SourceOptionGroup = nil
	}
	if resp.OptionGroup.VpcId != nil {
		ko.Status.VPCID = resp.OptionGroup.VpcId
	} else {
		ko.Status.VPCID = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateOptionGroupInput, error) {
	res := &svcsdk.CreateOptionGroupInput{}

	if r.ko.Spec.EngineName != nil {
		res.EngineName = r.ko.Spec.EngineName
	}
	if r.ko.Spec.MajorEngineVersion != nil {
		res.MajorEngineVersion = r.ko.Spec.MajorEngineVersion
	}
	if r.ko.Spec.Description != nil {
		res.OptionGroupDescription = r.ko.Spec.Description
	}
	if r.ko.Spec.Name != nil {
		res.OptionGroupName = r.ko.Spec.Name
	}
	if r.ko.Spec.Tags != nil {
		f4 := []svcsdktypes.Tag{}
		for _, f4iter := range r.ko.Spec.Tags {
			f4elem := &svcsdktypes.Tag{}
			if f4iter.Key != nil {
				f4elem.Key = f4iter.Key
			}
			if f4iter.Value != nil {
				f4elem.Value = f4iter.Value
			}
			f4 = append(f4, *f4elem)
		}
		res.Tags = f4
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	if delta.DifferentAt("Spec.Tags") {
		if err = rm.syncTags(ctx, desired, latest); err != nil {
			return nil, err
		}
	}

	if !delta.DifferentExcept("Spec.Tags") {
		return desired, nil
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.ModifyOptionGroupOutput
	_ = resp
	resp, err = rm.sdkapi.ModifyOptionGroup(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "ModifyOptionGroup", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.OptionGroup.AllowsVpcAndNonVpcInstanceMemberships != nil {
		ko.Status.AllowsVPCAndNonVPCInstanceMemberships = resp.OptionGroup.AllowsVpcAndNonVpcInstanceMemberships
	} else {
		ko.Status.AllowsVPCAndNonVPCInstanceMemberships = nil
	}
	if resp.OptionGroup.CopyTimestamp != nil {
		ko.Status.CopyTimestamp = &metav1.Time{*resp.OptionGroup.CopyTimestamp}
	} else {
		ko.Status.CopyTimestamp = nil
	}
	if resp.OptionGroup.EngineName != nil {
		ko.Spec.EngineName = resp.OptionGroup.EngineName
	} else {
		ko.Spec.EngineName = nil
	}
	if resp.OptionGroup.MajorEngineVersion != nil {
		ko.Spec.MajorEngineVersion = resp.OptionGroup.MajorEngineVersion
	} else {
		ko.Spec.MajorEngineVersion = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.OptionGroup.OptionGroupArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.OptionGroup.OptionGroupArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.OptionGroup.OptionGroupDescription != nil {
		ko.Spec.Description = resp.OptionGroup.OptionGroupDescription
	} else {
		ko.Spec.Description = nil
	}
	if resp.OptionGroup.OptionGroupName != nil {
		ko.Spec.Name = resp.OptionGroup.OptionGroupName
	} else {
		ko.Spec.Name = nil
	}
	if resp.OptionGroup.Options != nil {
		f7 := []*svcapitypes.Option{}
		for _, f7iter := range resp.OptionGroup.Options {
			f7elem := &svcapitypes.Option{}
			if f7iter.DBSecurityGroupMemberships != nil {
				f7elemf0 := []*svcapitypes.DBSecurityGroupMembership{}
				for _, f7elemf0iter := range f7iter.DBSecurityGroupMemberships {
					f7elemf0elem := &svcapitypes.DBSecurityGroupMembership{}
					if f7elemf0iter.DBSecurityGroupName != nil {
						f7elemf0elem.DBSecurityGroupName = f7elemf0iter.DBSecurityGroupName
					}
					if f7elemf0iter.Status != nil {
						f7elemf0elem.Status = f7elemf0iter.Status
					}
					f7elemf0 = append(f7elemf0, f7elemf0elem)
				}
				f7elem.DBSecurityGroupMemberships = f7elemf0
			}
			if f7iter.OptionDescription != nil {
				f7elem.OptionDescription = f7iter.OptionDescription
			}
			if f7iter.OptionName != nil {
				f7elem.OptionName = f7iter.OptionName
			}
			if f7iter.OptionSettings != nil {
				f7elemf3 := []*svcapitypes.OptionSetting{}
				for _, f7elemf3iter := range f7iter.OptionSettings {
					f7elemf3elem := &svcapitypes.OptionSetting{}
					if f7elemf3iter.AllowedValues != nil {
						f7elemf3elem.AllowedValues = f7elemf3iter.AllowedValues
					}
					if f7elemf3iter.ApplyType != nil {
						f7elemf3elem.ApplyType = f7elemf3iter.ApplyType
					}
					if f7elemf3iter.DataType != nil {
						f7elemf3elem.DataType = f7elemf3iter.DataType
					}
					if f7elemf3iter.DefaultValue != nil {
						f7elemf3elem.DefaultValue = f7elemf3iter.DefaultValue
					}
					if f7elemf3iter.Description != nil {
						f7elemf3elem.Description = f7elemf3iter.Description
					}
					if f7elemf3iter.IsCollection != nil {
						f7elemf3elem.IsCollection = f7elemf3iter.IsCollection
					}
					if f7elemf3iter.IsModifiable != nil {
						f7elemf3elem.IsModifiable = f7elemf3iter.IsModifiable
					}
					if f7elemf3iter.Name != nil {
						f7elemf3elem.Name = f7elemf3iter.Name
					}
					if f7elemf3iter.Value != nil {
						f7elemf3elem.Value = f7elemf3iter.Value
					}
					f7elemf3 = append(f7elemf3, f7elemf3elem)
				}
				f7elem.OptionSettings = f7elemf3
			}
			if f7iter.OptionVersion != nil {
				f7elem.OptionVersion = f7iter.OptionVersion
			}
			if f7iter.Permanent != nil {
				f7elem.Permanent = f7iter.Permanent
			}
			if f7iter.Persistent != nil {
				f7elem.Persistent = f7iter.Persistent
			}
			if f7iter.Port != nil {
				portCopy := int64(*f7iter.Port)
				f7elem.Port = &portCopy
			}
			if f7iter.VpcSecurityGroupMemberships != nil {
				f7elemf8 := []*svcapitypes.VPCSecurityGroupMembership{}
				for _, f7elemf8iter := range f7iter.VpcSecurityGroupMemberships {
					f7elemf8elem := &svcapitypes.VPCSecurityGroupMembership{}
					if f7elemf8iter.Status != nil {
						f7elemf8elem.Status = f7elemf8iter.Status
					}
					if f7elemf8iter.VpcSecurityGroupId != nil {
						f7elemf8elem.VPCSecurityGroupID = f7elemf8iter.VpcSecurityGroupId
					}
					f7elemf8 = append(f7elemf8, f7elemf8elem)
				}
				f7elem.VPCSecurityGroupMemberships = f7elemf8
			}
			f7 = append(f7, f7elem)
		}
		ko.Status.Options = f7
	} else {
		ko.Status.Options = nil
	}
	if resp.OptionGroup.SourceAccountId != nil {
		ko.Status.SourceAccountID = resp.OptionGroup.SourceAccountId
	} else {
		ko.Status.SourceAccountID = nil
	}
	if resp.OptionGroup.SourceOptionGroup != nil {
		ko.Status.SourceOptionGroup = resp.OptionGroup.SourceOptionGroup
	} else {
		ko.Status.SourceOptionGroup = nil
	}
	if resp.OptionGroup.VpcId != nil {
		ko.Status.VPCID = resp.OptionGroup.VpcId
	} else {
		ko.Status.VPCID = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.ModifyOptionGroupInput, error) {
	res := &svcsdk.ModifyOptionGroupInput{}

	if r.ko.Spec.Name != nil {
		res.OptionGroupName = r.ko.Spec.Name
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteOptionGroupOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteOptionGroup(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteOptionGroup", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteOptionGroupInput, error) {
	res := &svcsdk.DeleteOptionGroupInput{}

	if r.ko.Spec.Name != nil {
		res.OptionGroupName = r.ko.Spec.Name
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.OptionGroup,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	// No terminal_errors specified for this resource in generator config
	return false
}
