// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// OptionGroupSpec defines the desired state of OptionGroup.
//

type OptionGroupSpec struct {

	// The description of the option group.
	// +kubebuilder:validation:Required
	Description *string `json:"description"`
	// The name of the engine to associate this option group with.
	//
	// Valid Values:
	//
	//   - db2-ae
	//
	//   - db2-se
	//
	//   - mariadb
	//
	//   - mysql
	//
	//   - oracle-ee
	//
	//   - oracle-ee-cdb
	//
	//   - oracle-se2
	//
	//   - oracle-se2-cdb
	//
	//   - postgres
	//
	//   - sqlserver-ee
	//
	//   - sqlserver-se
	//
	//   - sqlserver-ex
	//
	//   - sqlserver-web
	//
	// +kubebuilder:validation:Required
	EngineName *string `json:"engineName"`
	// Specifies the major version of the engine that this option group should be
	// associated with.
	// +kubebuilder:validation:Required
	MajorEngineVersion *string `json:"majorEngineVersion"`
	// Specifies the name of the option group to be created.
	//
	// Constraints:
	//
	//   - Must be 1 to 255 letters, numbers, or hyphens
	//
	//   - First character must be a letter
	//
	//   - Can't end with a hyphen or contain two consecutive hyphens
	//
	// Example: myoptiongroup
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// Tags to assign to the option group.
	Tags []*Tag `json:"tags,omitempty"`
}

// OptionGroupStatus defines the observed state of OptionGroup
type OptionGroupStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// Indicates whether this option group can be applied to both VPC and non-VPC
	// instances. The value true indicates the option group can be applied to both
	// VPC and non-VPC instances.
	// +kubebuilder:validation:Optional
	AllowsVPCAndNonVPCInstanceMemberships *bool `json:"allowsVPCAndNonVPCInstanceMemberships,omitempty"`
	// Indicates when the option group was copied.
	// +kubebuilder:validation:Optional
	CopyTimestamp *metav1.Time `json:"copyTimestamp,omitempty"`
	// Indicates what options are available in the option group.
	// +kubebuilder:validation:Optional
	Options []*Option `json:"options,omitempty"`
	// Specifies the Amazon Web Services account ID for the option group from which
	// this option group is copied.
	// +kubebuilder:validation:Optional
	SourceAccountID *string `json:"sourceAccountID,omitempty"`
	// Specifies the name of the option group from which this option group is copied.
	// +kubebuilder:validation:Optional
	SourceOptionGroup *string `json:"sourceOptionGroup,omitempty"`
	// If AllowsVpcAndNonVpcInstanceMemberships is false, this field is blank. If
	// AllowsVpcAndNonVpcInstanceMemberships is true and this field is blank, then
	// this option group can be applied to both VPC and non-VPC instances. If this
	// field contains a value, then this option group can only be applied to instances
	// that are in the VPC indicated by this field.
	// +kubebuilder:validation:Optional
	VPCID *string `json:"vpcID,omitempty"`
}

// OptionGroup is the Schema for the OptionGroups API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type OptionGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              OptionGroupSpec   `json:"spec,omitempty"`
	Status            OptionGroupStatus `json:"status,omitempty"`
}

// OptionGroupList contains a list of OptionGroup
// +kubebuilder:object:root=true
type OptionGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OptionGroup `json:"items"`
}

func init() {
	SchemeBuilder.Register(&OptionGroup{}, &OptionGroupList{})
}
