name: unit-test
on:
  # Allow manual trigger
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
      - Makefile
      - go.mod
      - go.sum

jobs:
  build:
    name: make test
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: make test
        run: make test
